

//PLANTILLAS
const plantillasJugadores = {
  "Nacional": [
  { nombre: "F.Armani", edad: 39, media: 73, posicion: "PO", foto: "img/jugadores/g10/nac/armani.png", nacionalidad: "argentina" },
  { nombre: "M.Casco", edad: 38, media: 70, posicion: "LI", foto: "img/jugadores/g10/nac/casco.png", nacionalidad: "argentina" },
  { nombre: "W.Tesillo", edad: 36, media: 73, posicion: "DFC", foto: "img/jugadores/g10/nac/tesillo.png" },
  { nombre: "C.Haydar", edad: 25, media: 68, posicion: "DFC", foto: "img/jugadores/g10/nac/haydar.png" },
  { nombre: "A.Roman", edad: 30, media: 72, posicion: "LD", foto: "img/jugadores/g10/nac/roman.png" },
  { nombre: "E.Cardona", edad: 33, media: 73, posicion: "MO", foto: "img/jugadores/g10/nac/cardona.png" },
  { nombre: "J.M.Zapata", edad: 26, media: 71, posicion: "MD", foto: "img/jugadores/g10/nac/zapata.png" },
  { nombre: "J.Rengifo", edad: 21, media: 71, posicion: "MO", foto: "img/jugadores/g10/nac/rengifo.png" },
  { nombre: "A.Sarmiento", edad: 28, media: 72, posicion: "EI", foto: "img/jugadores/g10/nac/sarmiento.png" },
  { nombre: "A.Morelos", edad: 30, media: 75, posicion: "DC", foto: "img/jugadores/g10/nac/morelos.png" },
  { nombre: "N.Rodriguez", edad: 22, media: 66, posicion: "ED", foto: "img/jugadores/g10/nac/nico.png" },

  { nombre: "L.Marquinez", edad: 23, media: 68, posicion: "PO", foto: "img/jugadores/g10/nac/marquinez.png" },
  { nombre: "N.Parra", edad: 20, media: 64, posicion: "DFC", foto: "img/jugadores/g10/nac/neider.png" },
  { nombre: "Simon G.", edad: 21, media: 66, posicion: "DFC", foto: "img/jugadores/g10/nac/simon.png" },
  { nombre: "Yeicar P.", edad: 23, media: 67, posicion: "LD", foto: "img/jugadores/g10/nac/yeicar.png" },
  { nombre: "S.Velasquez", edad: 23, media: 66, posicion: "LI", foto: "img/jugadores/g10/nac/samuel.png" },
  { nombre: "M.Uribe", edad: 35, media: 72, posicion: "MD", foto: "img/jugadores/g10/nac/uribe.png" },
  { nombre: "J.Campuzano", edad: 30, media: 73, posicion: "MD", foto: "img/jugadores/g10/nac/campuzano.png" },
  { nombre: "E.Rivero", edad: 20, media: 64, posicion: "MD" },
  { nombre: "Ian Poveda", edad: 26, media: 66, posicion: "ED" },
  { nombre: "A.Reyes", edad: 26, media: 66, posicion: "DFC" },
  { nombre: "E.Cabrera", edad: 23, media: 66, posicion: "M0", nacionalidad: "argentina" },
  { nombre: "M.Moreno", edad: 29, media: 68, posicion: "EI", foto: "img/jugadores/g10/nac/marlos.png" },
  { nombre: "K.Parra", edad: 23, media: 70, posicion: "EI", foto: "img/jugadores/g10/nac/parra.png" },
  { nombre: "C.Arango", edad: 31, media: 72, posicion: "DC", foto: "img/jugadores/g10/nac/chicho.png" },

  { nombre: "R.Higuita", edad: 18, media: 84, posicion: "PO", foto: "img/jugadores/LY/higuita.png", leyenda: true, premium: true },
  { nombre: "A.Escobar", edad: 18, media: 84, posicion: "DFC", foto: "img/jugadores/LY/escobar.png", leyenda: true, premium: true },
  { nombre: "V.Aristizabal", edad: 18, media: 84, posicion: "DC", foto: "img/jugadores/LY/aristi.png", leyenda: true, premium: true }
],
"Millonarios": [
  { nombre: "J.Burrai", edad: 35, media: 67, posicion: "PO", foto: "img/jugadores/g10/mil/burrai.png", nacionalidad: "ecuador" },
  { nombre: "S.Valencia", edad: 30, media: 72, posicion: "LI", foto: "img/jugadores/g10/mil/sebas_valencia.png" },
  { nombre: "J.Arias", edad: 33, media: 67, posicion: "DFC", foto: "img/jugadores/g10/mil/jorge_arias.png" },
  { nombre: "S.Mosquera", edad: 32, media: 67, posicion: "DFC", foto: "img/jugadores/g10/mil/sergio_mosquera.png" },
  { nombre: "A.Llinás", edad: 29, media: 72, posicion: "DFC", foto: "img/jugadores/g10/mil/llinas.png" },
  { nombre: "Jhomier G.", edad: 25, media: 67, posicion: "LD", foto: "img/jugadores/g10/mil/jhomier.png" },
  { nombre: "R.Ureña", edad: 33, media: 68, posicion: "MD", foto: "img/jugadores/g10/mil/urena.png", nacionalidad: "chile" },
  { nombre: "M.Garcia", edad: 27, media: 66, posicion: "MD", foto: "img/jugadores/g10/mil/mateo_garcia.png" },
  { nombre: "F.Chaverra", edad: 26, media: 68, posicion: "EI", foto: "img/jugadores/g10/mil/francisco_chaverra.png" },
  { nombre: "Leo Castro", edad: 34, media: 70, posicion: "DC", foto: "img/jugadores/g10/mil/leo_castro.png" },
  { nombre: "R.Contreras", edad: 30, media: 72, posicion: "DC", foto: "img/jugadores/g10/mil/contreras.png", nacionalidad: "argentina" },

  { nombre: "J.Aguirre", edad: 34, media: 64, posicion: "PO", foto: "img/jugadores/g10/mil/aguirre.png" },
  { nombre: "D.Banguero", edad: 36, media: 64, posicion: "LI", foto: "img/jugadores/g10/mil/danovis.png" },
  { nombre: "S.Martin", edad: 20, media: 63, posicion: "LD", foto: "img/jugadores/g10/mil/samuel_martin.png"},
  { nombre: "Moreno Paz", edad: 24, media: 61, posicion: "DFC" },
  { nombre: "C.Sarabia", edad: 21, media: 62, posicion: "LD" },
  { nombre: "S.Barreiro", edad: 32, media: 71, posicion: "DFC" , foto: "img/jugadores/g10/mil/barreiro.png" },
  { nombre: "D.Ruiz", edad: 25, media: 68, posicion: "EI" , foto: "img/jugadores/g10/mil/daniel_ruiz.png"},
  { nombre: "Darwin Quintero", edad: 38, media: 65, posicion: "MO", foto: "img/jugadores/g10/mil/darwin.png" },
  { nombre: "S.Vega", edad: 28, media: 63, posicion: "MD", foto: "img/jugadores/g10/mil/vega.png" },
  { nombre: "D.Mackalister", edad: 39, media: 65, posicion: "MO", foto: "img/jugadores/g10/mil/macka.png" },
  { nombre: "Leonai", edad: 31, media: 66, posicion: "MD", nacionalidad: "brasil"},
  { nombre: "S.del Castillo", edad: 21, media: 65, posicion: "ED", foto: "img/jugadores/g10/mil/viveros_castillo.png" },
  { nombre: "J.Angulo", edad: 24, media: 65, posicion: "EI", foto: "img/jugadores/g10/mil/julian_angulo.png" },
  { nombre: "Andrey E.", edad: 32, media: 68, posicion: "EI", foto: "img/jugadores/g10/mil/andrey.png" },

  { nombre: "Di Stefano", edad: 18, media: 84, posicion: "MO", foto: "img/jugadores/LY/distafano.png", nacionalidad: "argentina", leyenda: true, premium: true },
  { nombre: "A.Iguaran", edad: 18, media: 84, posicion: "DC", foto: "img/jugadores/LY/arnoldo.png", leyenda: true, premium: true },
  { nombre: "R.Robayo", edad: 18, media: 84, posicion: "MD", foto: "img/jugadores/LY/robayo.png", leyenda: true, premium: true }
],
"América": [
  { nombre: "Jean", edad: 30, media: 71, posicion: "PO", foto: "img/jugadores/g10/ame/jean.png", nacionalidad: "brasil" },
  { nombre: "O.Bertel", edad: 29, media: 66, posicion: "LI", foto: "img/jugadores/g10/ame/bertel.png" },
  { nombre: "M.Torres", edad: 30, media: 68, posicion: "DFC", foto: "img/jugadores/g10/ame/marlon.png" },
  { nombre: "N.Hernandez", edad: 28, media: 68, posicion: "DFC" },
  { nombre: "Mateo C.", edad: 23, media: 69, posicion: "LD", foto: "img/jugadores/g10/ame/castillo.png" },
  { nombre: "Josen E.", edad: 21, media: 67, posicion: "MD", foto: "img/jugadores/g10/ame/josen.png" },
  { nombre: "R.Carrascal", edad: 33, media: 70, posicion: "MO", foto: "img/jugadores/g10/ame/carrascal.png" },
  { nombre: "Y.Guzman", edad: 28, media: 73, posicion: "MO", foto: "img/jugadores/g10/ame/guzman.png" },
  { nombre: "Tilman P.", edad: 20, media: 63, posicion: "EI" },
  { nombre: "T.Angel", edad: 23, media: 68, posicion: "DC", foto: "img/jugadores/g10/ame/tomas.png" },
  { nombre: "J.Murillo", edad: 30, media: 65, posicion: "ED", foto: "img/jugadores/g10/ame/murillo.png", nacionalidad: "venezuela" },

  { nombre: "J.P. Montoya", edad: 27, media: 65, posicion: "PO", foto: "img/jugadores/g10/ame/montoya.png" },
  { nombre: "D.Rosero", edad: 32, media: 66, posicion: "DFC", foto: "img/jugadores/g10/ame/rosero.png" },
  { nombre: "B.Cordoba", edad: 26, media: 67, posicion: "DFC", foto: "img/jugadores/g10/ame/cordoba.png" },
  { nombre: "C.Tovar", edad: 28, media: 66, posicion: "DFC", foto: "img/jugadores/g10/ame/tovar.png" },
  { nombre: "Yhormar H.", edad: 29, media: 67, posicion: "LD", foto: "img/jugadores/g10/ame/yhormar.png" },
  { nombre: "M.Mina", edad: 27, media: 65, posicion: "LI", foto: "img/jugadores/g10/ame/mina.png" },
  { nombre: "Yani Q.", edad: 24, media: 67, posicion: "MD", foto: "img/jugadores/g10/ame/yani.png" },
  { nombre: "J.Cavadia", edad: 20, media: 65, posicion: "MD" },
  { nombre: "J.Lucumi", edad: 22, media: 65, posicion: "EI"},
  { nombre: "D.Valencia", edad: 30, media: 69, posicion: "DC", foto: "img/jugadores/g10/ame/valencia.png", nacionalidad: "ecuador" },
  { nombre: "A.Ramos", edad: 40, media: 66, posicion: "DC", foto: "img/jugadores/g10/ame/ramos.png" },
  { nombre: "D.Borrero", edad: 24, media: 66, posicion: "EI", foto: "img/jugadores/g10/ame/borrero.png" },
  { nombre: "E.Tortolero", edad: 28, media: 66, posicion: "EI", foto: "img/jugadores/g10/ame/tortolero.png", nacionalidad: "venezuela" },
  { nombre: "L.Quiñones", edad: 35, media: 68, posicion: "ED", foto: "img/jugadores/g10/ame/quinones.png" },

  { nombre: "W.Ortiz", edad: 18, media: 83, posicion: "MO", foto: "img/jugadores/LY/willi.png", leyenda: true, premium: true },
  { nombre: "R.Gareca", edad: 18, media: 83, posicion: "DC", foto: "img/jugadores/LY/gareca.png", nacionalidad: "peru", leyenda: true, premium: true },
  { nombre: "A. de Avila", edad: 18, media: 83, posicion: "MD", foto: "img/jugadores/LY/pipa.png", leyenda: true, premium: true }
],

"Junior": [
  { nombre: "M.Silveira", edad: 26, media: 72, posicion: "PO", foto: "img/jugadores/g10/jun/silveira.png", nacionalidad: "uruguay" },
  { nombre: "Y.Suarez", edad: 29, media: 68, posicion: "LI"},
  { nombre: "Pablo Ortiz", edad: 26, media: 67, posicion: "DFC", foto: "img/jugadores/g10/jun/pablo_ortiz.png" },
  { nombre: "J.Peña", edad: 26, media: 67, posicion: "DFC", foto: "img/jugadores/g10/jun/jermein.png" },
  { nombre: "E.Herrera", edad: 27, media: 65, posicion: "LD", foto: "img/jugadores/g10/jun/herrera.png" },
  { nombre: "J.Rivas", edad: 29, media: 70, posicion: "MD", foto: "img/jugadores/g10/jun/rivas.png" },
  { nombre: "G.Celis", edad: 33, media: 68, posicion: "MD", foto: "img/jugadores/g10/jun/celis.png" },
  { nombre: "J.Sarmiento", edad: 26, media: 66, posicion: "MO", foto: "img/jugadores/g10/jun/sarmiento.png" },
  { nombre: "B.Castrillon", edad: 27, media: 66, posicion: "EI", foto: "img/jugadores/g10/jun/castrillon.png" },
  { nombre: "L.Muriel", edad: 35, media: 72, posicion: "DC", foto: "img/jugadores/g10/jun/muriel.png" },
  { nombre: "C.Barrios", edad: 28, media: 68, posicion: "ED", foto: "img/jugadores/g10/jun/cristian_barrios.png" },

  { nombre: "J.Martinez", edad: 32, media: 66, posicion: "PO", foto: "img/jugadores/g10/jun/martinez.png" },
  { nombre: "J.Pestaña", edad: 28, media: 66, posicion: "DFC", foto: "img/jugadores/g10/jun/pestana.png" },
  { nombre: "D.Rivera", edad: 27, media: 67, posicion: "DFC", foto:  "img/jugadores/g10/jun/rivera.png" },
  { nombre: "F.Correa", edad: 20, media: 62, posicion: "LI" },
  { nombre: "Y.Chara", edad: 35, media: 65, posicion: "MO", foto: "img/jugadores/g10/jun/chara.png" },
  { nombre: "F.Angel", edad: 25, media: 67, posicion: "MD", foto: "img/jugadores/g10/jun/angel.png" },
  { nombre: "J.Rios", edad: 34, media: 67, posicion: "MD", foto:  "img/jugadores/g10/jun/rios.png" },
  { nombre: "H.Rivera", edad: 33, media: 64, posicion: "MD" },
  { nombre: "J.Canchimbo", edad: 20, media: 65, posicion: "ED", foto: "img/jugadores/g10/jun/canchimbo.png" },
  { nombre: "K.Perez", edad: 29, media: 65, posicion: "ED", foto: "img/jugadores/g10/jun/kevin_perez.png" },
  { nombre: "Deiber C.", edad: 26, media: 67, posicion: "EI", foto: "img/jugadores/g10/jun/deiber.png" },
  { nombre: "F.Fydriszewski", edad: 33, media: 70, posicion: "DC", foto: "img/jugadores/g10/jun/polaco.png", nacionalidad: "argentina" },
  { nombre: "G.Paiva", edad: 28, media: 67, posicion: "DC", foto: "img/jugadores/g10/jun/paiva.png", nacionalidad: "paraguay" },
  { nombre: "T.Gutierrez", edad: 41, media: 68, posicion: "DC", foto: "img/jugadores/g10/jun/teo.png" },

  { nombre: "C.Valderrama", edad: 18, media: 83, posicion: "MO", foto: "img/jugadores/LY/pibe.png", leyenda: true, premium: true },
  { nombre: "I.Valenciano", edad: 18, media: 83, posicion: "DC", foto: "img/jugadores/LY/valenciano.png", leyenda: true, premium: true },
  { nombre: "G.Hernandez", edad: 18, media: 83, posicion: "ED", foto: "img/jugadores/LY/gio.png", leyenda: true, premium: true }
],
"Santa Fe": [
  { nombre: "A.Marmolejo", edad: 34, media: 72, posicion: "PO", foto: "img/jugadores/g10/sfe/marmolejo.png" },
  { nombre: "C.Mafla", edad: 33, media: 68, posicion: "LI", foto: "img/jugadores/g10/sfe/mafla.png" },
  { nombre: "Victor M.", edad: 31, media: 67, posicion: "DFC", foto: "img/jugadores/g10/sfe/victor_moreno.png" },
  { nombre: "E.Olivera", edad: 36, media: 67, posicion: "DFC", foto: "img/jugadores/g10/sfe/olivera.png", nacionalidad: "argentina" },
  { nombre: "H.Palacios", edad: 33, media: 66, posicion: "LD", foto: "img/jugadores/g10/sfe/helibelton.png" },
  { nombre: "Yilmar V.", edad: 26, media: 66, posicion: "MD", foto:  "img/jugadores/g10/sfe/yilmar.png" },
  { nombre: "D.Torres", edad: 36, media: 68, posicion: "MD", foto: "img/jugadores/g10/sfe/daniel_torres.png" },
  { nombre: "Ewil M.", edad: 26, media: 66, posicion: "MD", foto:  "img/jugadores/g10/sfe/ewil.png" },
  { nombre: "O.Frasica", edad: 33, media: 67, posicion: "EI", foto: "img/jugadores/g10/sfe/frasica.png" },
  { nombre: "H.Rodallega", edad: 40, media: 72, posicion: "DC", foto: "img/jugadores/g10/sfe/hugo.png" },
  { nombre: "L.Palacios", edad: 25, media: 65, posicion: "ED", foto:  "img/jugadores/g10/sfe/luis_palacios.png" },

  { nombre: "W.Asprilla", edad: 27, media: 66, posicion: "PO", foto:  "img/jugadores/g10/sfe/weimar.png" },
   { nombre: "J.Espitia", edad: 26, media: 63, posicion: "PO", foto: "img/jugadores/g10/sfe/espitia.png" },
  { nombre: "I.Scarpeta", edad: 30, media: 65, posicion: "DFC", foto: "img/jugadores/g10/sfe/scarpeta.png" },
  { nombre: "J.S. Quintero", edad: 31, media: 64, posicion: "DFC"},
  { nombre: "K.Balanta", edad: 29, media: 66, posicion: "DFC", foto: "img/jugadores/g10/sfe/kevin_balanta.png" },
  { nombre: "Mateo P.", edad: 29, media: 65, posicion: "LD", foto: "img/jugadores/g10/sfe/puerta.png" },
  { nombre: "Jei Angulo", edad: 30, media: 64, posicion: "LI" },
  { nombre: "A.Zapata", edad: 31, media: 65, posicion: "MO", foto:  "img/jugadores/g10/sfe/alexis.png" },
  { nombre: "Jhojan T.", edad: 23, media: 66, posicion: "MD", foto: "img/jugadores/g10/sfe/kante.png" },
  { nombre: "F.Fagundez", edad: 26, media: 68, posicion: "MO", foto: "img/jugadores/g10/sfe/fagundez.png", nacionalidad: "uruguay" },
  { nombre: "K.Toscano", edad: 22, media: 65, posicion: "MD", foto: "img/jugadores/g10/sfe/kilian.png" },
  { nombre: "M.Lovera", edad: 27, media: 68, posicion: "MO", foto: "img/jugadores/g10/sfe/lovera.png" },
  { nombre: "J.Obrian", edad: 31, media: 67, posicion: "ED", foto: "img/jugadores/g10/sfe/obrian.png" },
  { nombre: "N.Bustos", edad: 26, media: 68, posicion: "DC", foto: "img/jugadores/g10/sfe/bustos.png", nacionalidad: "argentina" },

  { nombre: "Omar Perez", edad: 18, media: 82, posicion: "MO", foto: "img/jugadores/LY/omar.png", nacionalidad: "argentina", leyenda: true, premium: true },
  { nombre: "A.Cañon", edad: 18, media: 82, posicion: "MO", foto: "img/jugadores/LY/canon.png", leyenda: true, premium: true },
  { nombre: "L.Preciado", edad: 18, media: 82, posicion: "DC", foto: "img/jugadores/LY/leider.png", leyenda: true, premium: true }
],

 "Cali": [
  { nombre: "P.Gallese", edad: 36, media: 72, posicion: "PO", foto: "img/jugadores/g10/cal/gallese.png", nacionalidad: "peru" },
  { nombre: "E.Velasco", edad: 34, media: 67, posicion: "LI", foto: "img/jugadores/g10/cal/velasco.png" },
  { nombre: "F.Alvarez", edad: 22, media: 66, posicion: "DFC", foto: "img/jugadores/g10/cal/alvarez.png" },
  { nombre: "Keimer S.", edad: 20, media: 65, posicion: "DFC", foto: "img/jugadores/g10/cal/keimer.png" },
  { nombre: "J.Moya", edad: 33, media: 67, posicion: "DFC", foto: "img/jugadores/g10/cal/moya.png" },
  { nombre: "F.Viafara", edad: 34, media: 65, posicion: "LD", foto: "img/jugadores/g10/cal/viafara.png" },
  { nombre: "D.Giraldo", edad: 34, media: 65, posicion: "MD", foto: "img/jugadores/g10/cal/giraldo.png" },
  { nombre: "G.Cuellar", edad: 33, media: 67, posicion: "MD", foto: "img/jugadores/g10/cal/cuellar.png" },
  { nombre: "N.Benedetti", edad: 29, media: 67, posicion: "MO", foto: "img/jugadores/g10/cal/benedetti.png" },
  { nombre: "J.Dinenno", edad: 31, media: 67, posicion: "DC", foto: "img/jugadores/g10/cal/dinenno.png", nacionalidad: "argentina" },
  { nombre: "Titi Rodríguez", edad: 27, media: 68, posicion: "DC", foto: "img/jugadores/g10/cal/titi.png" },

  { nombre: "A.Rodriguez", edad: 25, media: 68, posicion: "PO", foto: "img/jugadores/g10/cal/alejo.png" },
  { nombre: "J.Caldera", edad: 24, media: 65, posicion: "DFC", foto: "img/jugadores/g10/cal/caldera.png" },
  { nombre: "Leyser C.", edad: 29, media: 67, posicion: "LD", foto:  "img/jugadores/g10/cal/leyser.png" },
  { nombre: "J.Tello", edad: 24, media: 62, posicion: "LI" },
  { nombre: "Kalazan S.", edad: 24, media: 65, posicion: "LI", foto: "img/jugadores/g10/cal/kalazan.png"},
  { nombre: "M.Orozco", edad: 18, media: 66, posicion: "MD", foto:  "img/jugadores/g10/cal/orozco.png" },
  { nombre: "E.Reynoso", edad: 30, media: 66, posicion: "MO", foto: "img/jugadores/g10/cal/bebelo.png", nacionalidad: "argentina" },
  { nombre: "R.Pajaro", edad: 24, media: 66, posicion: "MD", foto:  "img/jugadores/g10/cal/pajaro.png" },
  { nombre: "Johan M.", edad: 24, media: 67, posicion: "MO", foto:  "img/jugadores/g10/cal/honguito.png" },
  { nombre: "E.Bello", edad: 30, media: 70, posicion: "ED", foto: "img/jugadores/g10/cal/bello.png", nacionalidad: "venezuela" },
  { nombre: "C.Bacca", edad: 39, media: 69, posicion: "DC", foto: "img/jugadores/g10/cal/bacca.png"},
  { nombre: "A.Hurtado", edad: 39, media: 66, posicion: "EI", foto: "img/jugadores/g10/cal/aviles.png" },

  { nombre: "M.Calero", edad: 18, media: 82, posicion: "PO", foto: "img/jugadores/LY/calero.png", leyenda: true, premium: true },
  { nombre: "M.Yepes", edad: 18, media: 82, posicion: "DFC", foto: "img/jugadores/LY/yepes.png", leyenda: true, premium: true },
  { nombre: "A.Perez", edad: 18, media: 82, posicion: "MD", foto: "img/jugadores/LY/perez.png", leyenda: true, premium: true }
],

 "Medellín": [
  { nombre: "S.Ichazo", edad: 34, media: 67, posicion: "PO", foto: "img/jugadores/g10/dim/ichazo.png", nacionalidad: "uruguay" },
  { nombre: "F.Fabra", edad: 35, media: 72, posicion: "LI", foto: "img/jugadores/g10/dim/fabra.png" },
  { nombre: "J.Varela", edad: 28, media: 68, posicion: "DFC", foto: "img/jugadores/g10/dim/varela.png", nacionalidad: "uruguay" },
  { nombre: "K.Mantilla", edad: 22, media: 66, posicion: "DFC", foto: "img/jugadores/g10/dim/mantilla.png" },
  { nombre: "E.Mena", edad: 28, media: 67, posicion: "LD", foto: "img/jugadores/g10/dim/esneyder.png" },
  { nombre: "Diego M.", edad: 30, media: 65, posicion: "MD", foto: "img/jugadores/g10/dim/diego_moreno.png" },
  { nombre: "Didier M.", edad: 34, media: 72, posicion: "MD", foto: "img/jugadores/g10/dim/didier.png" },
  { nombre: "D.Cataño", edad: 34, media: 68, posicion: "MO", foto: "img/jugadores/g10/dim/daniel_catano.png" },
  { nombre: "A.Martegani", edad: 26, media: 68, posicion: "MO", foto: "img/jugadores/g10/dim/martegani.png", nacionalidad: "argentina" },
  { nombre: "J.Medina", edad: 31, media: 69, posicion: "DC", foto: "img/jugadores/g10/dim/medina.png" },
  { nombre: "J.J. Cordoba", edad: 23, media: 69, posicion: "ED", foto: "img/jugadores/g10/dim/cordoba.png" },
  
  { nombre: "E.Chaux", edad: 34, media: 67, posicion: "PO", foto:  "img/jugadores/g10/dim/chaux.png" },
  { nombre: "Hayen P.", edad: 26, media: 65, posicion: "LD", foto: "img/jugadores/g10/dim/hayen.png" },
  { nombre: "A.Simarra", edad: 26, media: 66, posicion: "DFC", foto: "img/jugadores/g10/dim/simarra.png" },
  { nombre: "L.Escorcia", edad: 22, media: 65, posicion: "DFC", foto: "img/jugadores/g10/dim/escorcia.png"},
  { nombre: "Jhan M.", edad: 20, media: 63, posicion: "LI"},
  { nombre: "A.Serna", edad: 28, media: 63, posicion: "MD"},
  { nombre: "Juanfer Q.", edad: 33, media: 80, posicion: "MO", foto: "img/jugadores/g10/dim/juanfer.png" },
  { nombre: "H.Loboa", edad: 20, media: 64, posicion: "MD", foto: "img/jugadores/g10/dim/loboa.png" },
  { nombre: "L.Berrio", edad: 28, media: 65, posicion: "MO"},
  { nombre: "Baldomero P.", edad: 34, media: 66, posicion: "MO", foto: "img/jugadores/g10/dim/baldomero.png" },
  { nombre: "J.Montaño", edad: 19, media: 64, posicion: "ED", foto:  "img/jugadores/g10/dim/montano.png" },
  { nombre: "G.Mancilla", edad: 17, media: 57, posicion: "ED"},
  { nombre: "Y.Gonzalez", edad: 32, media: 68, posicion: "ED", foto: "img/jugadores/g10/dim/yony.png" },
  { nombre: "C.Lucumi", edad: 26, media: 67, posicion: "DC", foto: "img/jugadores/g10/dim/lucumi.png" },

  { nombre: "J.M. Moreno", edad: 18, media: 82, posicion: "MO", foto: "img/jugadores/LY/charro.png", nacionalidad: "argentina", leyenda: true, premium: true },
  { nombre: "Mao Molina", edad: 18, media: 82, posicion: "EI", foto: "img/jugadores/LY/mao.png", leyenda: true, premium: true },
  { nombre: "J.Restrepo", edad: 18, media: 82, posicion: "MD", foto: "img/jugadores/LY/choronta.png", leyenda: true, premium: true }
],

"Tolima": [
  { nombre: "N.Volpi", edad: 33, media: 70, posicion: "PO", foto: "img/jugadores/g10/tol/volpi.png", nacionalidad: "brasil" },
  { nombre: "J.Hernandez", edad: 27, media: 65, posicion: "LI", foto: "img/jugadores/g10/tol/junior.png" },
  { nombre: "Jan Angulo", edad: 24, media: 66, posicion: "DFC", foto: "img/jugadores/g10/tol/jan_angulo.png" },
  { nombre: "A.Angulo", edad: 29, media: 67, posicion: "DFC", foto: "img/jugadores/g10/tol/anderson_angulo.png" },
  { nombre: "C.Arrieta", edad: 30, media: 66, posicion: "LD", foto: "img/jugadores/g10/tol/arrietta.png" },
  { nombre: "S.Guzman", edad: 28, media: 67, posicion: "MD", foto: "img/jugadores/g10/tol/mariachi.png" },
  { nombre: "B.Rovira", edad: 29, media: 66, posicion: "MD", foto: "img/jugadores/g10/tol/rovira.png" },
  { nombre: "Niche Sanchez", edad: 25, media: 68, posicion: "MO", foto: "img/jugadores/g10/tol/niche.png" },
  { nombre: "Ever V.", edad: 29, media: 66, posicion: "EI", foto: "img/jugadores/g10/tol/ever.png" },
  { nombre: "L.Sandoval", edad: 26, media: 66, posicion: "DC", foto: "img/jugadores/g10/tol/chino.png" },
  { nombre: "Jader V.", edad: 26, media: 65, posicion: "DC", foto: "img/jugadores/g10/tol/jader.png" },

  { nombre: "M.Ortega", edad: 31, media: 66, posicion: "PO", foto: "img/jugadores/g10/tol/ortega.png", nacionalidad: "mexico" },
  { nombre: "J.Mera", edad: 24, media: 65, posicion: "DFC", foto:  "img/jugadores/g10/tol/mera.png" },
  { nombre: "Y.Osorio", edad: 31, media: 67, posicion: "DFC", foto:  "img/jugadores/g10/tol/osorio.png", nacionalidad: "venezuela" },
  { nombre: "D.Pedrozo", edad: 22, media: 64, posicion: "DFC", foto: "img/jugadores/g10/tol/pedrozo.png" },
  { nombre: "Jherson M.", edad: 26, media: 66, posicion: "LD", foto: "img/jugadores/g10/tol/jherson.png" },
  { nombre: "S.Barbosa", edad: 22, media: 63, posicion: "LI"},
  { nombre: "Homer M.", edad: 22, media: 63, posicion: "MD", foto: "img/jugadores/g10/tol/homer.png"},
  { nombre: "C.Trujillo", edad: 27, media: 66, posicion: "MD", foto: "img/jugadores/g10/tol/trujillo.png" },
  { nombre: "J.Hurtado", edad: 22, media: 66, posicion: "DC", foto: "img/jugadores/g10/tol/hurtado.png" },
  { nombre: "Kelvin F.", edad: 22, media: 68, posicion: "EI", foto: "img/jugadores/g10/tol/kelvin.png" },
  { nombre: "E.Lopez", edad: 31, media: 67, posicion: "EI", foto: "img/jugadores/g10/tol/edwar_lopez.png" },
  { nombre: "A.Parra", edad: 29, media: 66, posicion: "EI", foto: "img/jugadores/g10/tol/adrian_parra.png" },

  { nombre: "W.Medina", edad: 18, media: 81, posicion: "DC", foto: "img/jugadores/LY/wilder.png", leyenda: true, premium: true },
  { nombre: "R.Ciciliano", edad: 18, media: 81, posicion: "MO", foto: "img/jugadores/LY/ciciliano.png", leyenda: true, premium: true },
],

"Once Caldas": [
  { nombre: "J.Parra", edad: 26, media: 68, posicion: "PO", foto: "img/jugadores/g10/onc/joan_parra.png" },
  { nombre: "A.Correa", edad: 32, media: 67, posicion: "LI", foto: "img/jugadores/g10/onc/correa.png" },
  { nombre: "J.Cardona", edad: 27, media: 65, posicion: "DFC", foto: "img/jugadores/g10/onc/jorge_cardona.png" },
  { nombre: "J.Castaño", edad: 27, media: 65, posicion: "DFC", foto: "img/jugadores/g10/onc/castano.png" },
  { nombre: "J.Cuesta", edad: 28, media: 66, posicion: "LD", foto: "img/jugadores/g10/onc/cuesta.png" },
  { nombre: "J.Alvarado", edad: 26, media: 66, posicion: "MD", foto: "img/jugadores/g10/onc/alvarado.png" },
  { nombre: "Jader Q.", edad: 25, media: 65, posicion: "MD", foto: "img/jugadores/g10/onc/jader_quinones.png" },
  { nombre: "A.Roa", edad: 33, media: 64, posicion: "MO", foto: "img/jugadores/g10/onc/roa.png" },
  { nombre: "Pipe Gomez", edad: 26, media: 67, posicion: "EI", foto: "img/jugadores/g10/onc/pipe.png" },
  { nombre: "J.Zapata", edad: 26, media: 69, posicion: "DC", foto: " img/jugadores/g10/onc/jefry.png" },
  { nombre: "M.Barrios", edad: 35, media: 67, posicion: "ED", foto: "img/jugadores/g10/onc/michael_barrios.png" },

  { nombre: "J.Camargo", edad: 28, media: 65, posicion: "PO", foto: "img/jugadores/g10/onc/camargo.png", nacionalidad: "venezuela" },
  { nombre: "J.Gallego", edad: 21, media: 59, posicion: "PO"},
  { nombre: "D.Marmolejo", edad: 22, media: 62, posicion: "DFC"},
  { nombre: "J.Riquett", edad: 36, media: 64, posicion: "DFC"},
  { nombre: "E.Navarro", edad: 26, media: 65, posicion: "LD", foto:  "img/jugadores/g10/onc/efrain.png" },
  { nombre: "D.Londoño", edad: 31, media: 67, posicion: "LI", foto:  "img/jugadores/g10/onc/londono.png" },
  { nombre: "A.Colorado", edad: 27, media: 66, posicion: "MD", foto: "img/jugadores/g10/onc/andres_colorado.png" },
  { nombre: "J.P. Nieto", edad: 33, media: 67, posicion: "MD", foto: "img/jugadores/g10/onc/nieto.png" },
  { nombre: "M.Zuleta", edad: 24, media: 66, posicion: "EI", foto: "img/jugadores/g10/onc/zuleta.png" },
  { nombre: "D.Moreno", edad: 40, media: 72, posicion: "DC", foto:  "img/jugadores/g10/onc/dayro.png" },
  { nombre: "Edwin Torres", edad: 28, media: 67, posicion: "ED", foto: "img/jugadores/g10/onc/edwin_torres.png" },

  { nombre: "S.Galvan Rey", edad: 18, media: 82, posicion: "DC", foto: "img/jugadores/LY/galvan.png", nacionalidad: "argentina", leyenda: true, premium: true },
  { nombre: "A.Valentierra", edad: 18, media: 82, posicion: "MO", foto: "img/jugadores/LY/arnulfo.png", leyenda: true, premium: true },
  { nombre: "J.C.Henao", edad: 18, media: 82, posicion: "PO", foto: "img/jugadores/LY/henao.png", leyenda: true, premium: true }
],

"Bucaramanga": [
  { nombre: "C.Fiermarin", edad: 28, media: 69, posicion: "PO", foto: "img/jugadores/g10/buc/fiermarin.png", nacionalidad: "uruguay" },
  { nombre: "J.C. Mosquera", edad: 24, media: 64, posicion: "LI", foto: "img/jugadores/g10/buc/juan_mosquera.png" },
  { nombre: "Jose G.", edad: 23, media: 65, posicion: "DFC", foto: "img/jugadores/g10/buc/jose_garcia.png" },
  { nombre: "M.Rea", edad: 28, media: 66, posicion: "DFC", foto: "img/jugadores/g10/buc/rea.png" },
  { nombre: "Aldair G.", edad: 28, media: 66, posicion: "LD", foto: "img/jugadores/g10/buc/aldair.png" },
  { nombre: "A.Zarate", edad: 27, media: 65, posicion: "MD", foto:  "img/jugadores/g10/buc/zarate.png" },
  { nombre: "L.Florez", edad: 30, media: 66, posicion: "MD", foto:  "img/jugadores/g10/buc/flores.png", nacionalidad: "venezuela" },
  { nombre: "F.Sambueza", edad: 37, media: 73, posicion: "MO", foto: "img/jugadores/g10/buc/sambueza.png", nacionalidad: "argentina" },
  { nombre: "F.Hinestroza", edad: 36, media: 66, posicion: "EI", foto: "img/jugadores/g10/buc/hinestroza.png" },
  { nombre: "L.Pons", edad: 36, media: 69, posicion: "DC", foto: "img/jugadores/g10/buc/pons.png", nacionalidad: "argentina" },
  { nombre: "E.Batalla", edad: 25, media: 72, posicion: "ED", foto: "img/jugadores/g10/buc/batalla.png" },

  { nombre: "D.Novoa", edad: 37, media: 66, posicion: "PO", foto: "img/jugadores/g10/buc/novoa.png" },
  { nombre: "L.Vasquez", edad: 30, media: 65, posicion: "PO"},
  { nombre: "C.Romaña", edad: 26, media: 66, posicion: "DFC", foto: "img/jugadores/g10/buc/romana.png" },
  { nombre: "Jose Ortiz", edad: 27, media: 67, posicion: "DFC", foto: "img/jugadores/g10/buc/ortiz.png" },
  { nombre: "K.Londoño", edad: 32, media: 67, posicion: "MO", foto: "img/jugadores/g10/buc/kevin_londono.png" },
  { nombre: "V.Cantillo", edad: 32, media: 66, posicion: "MD", foto: "img/jugadores/g10/buc/cantillo.png" },
  { nombre: "Fabry C.", edad: 34, media: 65, posicion: "MD", foto: "img/jugadores/g10/buc/fabry.png" },
  { nombre: "F.Charrupi", edad: 25, media: 65, posicion: "MD", foto: "img/jugadores/g10/buc/felix_charrupi.png" },
  { nombre: "Brandon C.", edad: 25, media: 62, posicion: "DC", foto: "img/jugadores/g10/buc/brandon.png" },
  { nombre: "J.F. Salazar", edad: 31, media: 65, posicion: "ED", foto: "img/jugadores/g10/buc/salazar.png" },
  { nombre: "O.Albornoz", edad: 30, media: 65, posicion: "EI", foto: "img/jugadores/g10/buc/albornoz.png" },

  { nombre: "A.Montanini", edad: 18, media: 79, posicion: "DC", foto: "img/jugadores/LY/americo.png", leyenda: true, premium: true }
],

//RESTO 1
"Pereira": [
  { nombre: "J.Martinez", edad: 20, media: 62, posicion: "PO" },
  { nombre: "T.Bovone", edad: 26, media: 63, posicion: "LI", foto: "img/jugadores/resto1/bovone.png" },
  { nombre: "S.Urrea", edad: 24, media: 63, posicion: "DFC", foto: "img/jugadores/resto1/urrea.png" },
  { nombre: "Danilo O.", edad: 33, media: 64, posicion: "DFC", foto: "img/jugadores/resto1/danilo_ortiz.png", nacionalidad: "paraguay" },
  { nombre: "W.Pacheco", edad: 31, media: 67, posicion: "LD", foto: "img/jugadores/resto1/walmer.png" },
  { nombre: "M.Aguirre", edad: 21, media: 58, posicion: "MD" },
  { nombre: "J.Bermudez", edad: 25, media: 63, posicion: "MD", foto: "img/jugadores/resto1/bermudez.png" },
  { nombre: "S.Acosta", edad: 31, media: 62, posicion: "MO", foto: "img/jugadores/resto1/acosta.png" },
  { nombre: "J.Largacha", edad: 22, media: 63, posicion: "EI", foto: "img/jugadores/resto1/largacha.png" },
  { nombre: "M.Perez", edad: 35, media: 65, posicion: "DC", foto: "img/jugadores/resto1/marco_perez.png" },
  { nombre: "A.Plata", edad: 35, media: 65, posicion: "ED", foto: "img/jugadores/resto1/plata.png" },

  { nombre: "Y.Gomez", edad: 26, media: 62, posicion: "PO", foto: "img/jugadores/resto1/yimy.png" },
  { nombre: "S.Aguilar", edad: 27, media: 64, posicion: "DFC", foto: "img/jugadores/resto1/aguilar.png" },
  { nombre: "R.Renteria", edad: 30, media: 65, posicion: "DFC" },
  { nombre: "F.Delgado", edad: 27, media: 62, posicion: "LI", foto: "img/jugadores/resto1/fabio.png" },
  { nombre: "Eber M.", edad: 24, media: 60, posicion: "LI"},
  { nombre: "J.Monroy", edad: 30, media: 64, posicion: "LD", foto: "img/jugadores/resto1/jordy.png", nacionalidad: "armenia" },
  { nombre: "D.Mendoza", edad: 25, media: 63, posicion: "MD" },
  { nombre: "Nicolas R.", edad: 22, media: 64, posicion: "MD", foto: "img/jugadores/resto1/nicolas_rengifo.png" },
  { nombre: "E.Moreno", edad: 32, media: 63, posicion: "MO"},
  { nombre: "Y.Quiñones", edad: 23, media: 65, posicion: "EI", foto: "img/jugadores/resto1/yuber.png" },
  { nombre: "J.Jordan", edad: 25, media: 65, posicion: "EI" },

  { nombre: "Jhonny Vasquez", edad: 18, media: 79, posicion: "MD", foto: "img/jugadores/LY/jhonny.png", leyenda: true, premium: true }
],

  "Pasto": [
  { nombre: "G.Banguera", edad: 30, media: 64, posicion: "PO", foto:  "img/jugadores/resto1/banguera.png" },
  { nombre: "M.Garavito", edad: 25, media: 65, posicion: "LI", foto:  "img/jugadores/resto1/garavito.png" },
  { nombre: "F.Torijano", edad: 37, media: 65, posicion: "DFC", foto: "img/jugadores/resto1/torijano.png" },
  { nombre: "N.Gil", edad: 29, media: 65, posicion: "DFC", foto: "img/jugadores/resto1/gil.png" },
  { nombre: "S.Jimenez", edad: 28, media: 66, posicion: "LD", foto:  "img/jugadores/resto1/jimenez.png" },
  { nombre: "H.Mansilla", edad: 34, media: 65, posicion: "MD", foto: "img/jugadores/resto1/harrinson.png" },
  { nombre: "E.Serje", edad: 30, media: 63, posicion: "MD", foto:  "img/jugadores/resto1/serje.png" },
  { nombre: "D.Chavez", edad: 28, media: 64, posicion: "MO", foto: "img/jugadores/resto1/chavez.png" },
  { nombre: "Mayer Gil", edad: 22, media: 64, posicion: "EI"},
  { nombre: "S.Cordoba", edad: 29, media: 65, posicion: "DC", foto: "img/jugadores/resto1/santiago_cordoba.png" },
  { nombre: "J.Micolta", edad: 24, media: 66, posicion: "ED" },

  { nombre: "Ederson C.", edad: 26, media: 65, posicion: "PO", foto: "img/jugadores/resto1/ederson.png" },
  { nombre: "Hervin G.", edad: 20, media: 63, posicion: "LI", foto: "img/jugadores/resto1/goyes.png" },
  { nombre: "J.Quiñones", edad: 36, media: 64, posicion: "DFC", foto: "img/jugadores/resto1/julian_quinones.png" },
  { nombre: "Joyce Ossa", edad: 28, media: 64, posicion: "DFC", foto: "img/jugadores/resto1/ossa.png" },
  { nombre: "Y.Goez", edad: 26, media: 65, posicion: "MD", foto: "img/jugadores/resto1/goez.png" },
  { nombre: "J.Perlaza", edad: 25, media: 65, posicion: "MD"},
  { nombre: "F.Leys", edad: 32, media: 65, posicion: "MD", foto: "img/jugadores/resto1/leys.png" },
  { nombre: "M.Pisano", edad: 34, media: 67, posicion: "MO", foto: "img/jugadores/resto1/pisano.png", nacionalidad: "argentina" },
  { nombre: "J.Obregon", edad: 29, media: 67, posicion: "DC", foto: "img/jugadores/resto1/obregon.png" },
  { nombre: "A.Ibarguen", edad: 34, media: 63, posicion: "EI", foto: "img/jugadores/resto1/ibarguen.png" },

  { nombre: "C.Hidalgo", edad: 18, media: 78, posicion: "DC", foto: "img/jugadores/LY/hidalgo.png", leyenda: true, premium: true }
],

"Alianza": [
  { nombre: "J.Wallens",     edad: 33, media: 64, posicion: "PO", foto:  "img/jugadores/resto1/wallens.png" },
  { nombre: "E.Banguero",    edad: 25, media: 63, posicion: "LI", foto: "img/jugadores/resto1/banguero.png" },
  { nombre: "J.Figueroa",    edad: 30, media: 63, posicion: "DFC", foto: "img/jugadores/resto1/figueroa.png" },
  { nombre: "P.Franco",      edad: 34, media: 64, posicion: "DFC", foto: "img/jugadores/resto1/franco.png" },
  { nombre: "K.Moreno",      edad: 25, media: 63, posicion: "DFC"},
  { nombre: "Y.Rosales",     edad: 25, media: 63, posicion: "LD", foto: "img/jugadores/resto1/yilson.png" },
  { nombre: "W.Fernandez",   edad: 28, media: 67, posicion: "MD", foto: "img/jugadores/resto1/wiston.png", nacionalidad: "uruguay" },
  { nombre: "Ever Meza",     edad: 25, media: 60, posicion: "MD"},
  { nombre: "C.Esparragoza", edad: 27, media: 64, posicion: "MD", foto: "img/jugadores/resto1/esparragosa.png" },
  { nombre: "Y.Londoño",     edad: 25, media: 61, posicion: "EI", foto: "img/jugadores/resto1/yeiner.png" },
  { nombre: "F.Pardo",       edad: 35, media: 65, posicion: "ED", foto: "img/jugadores/resto1/pardo.png" },

  { nombre: "J.Chaverra", edad: 33, media: 63, posicion: "PO"},
  { nombre: "E.Beltran",  edad: 26, media: 63, posicion: "PO", foto: "img/jugadores/resto1/esteban.png"},
  { nombre: "J.Viveros",  edad: 22, media: 63, posicion: "DFC"},
  { nombre: "I.Alba",     edad: 31, media: 65, posicion: "LD", foto: "img/jugadores/resto1/alba.png" },
  { nombre: "Jair C.",    edad: 29, media: 61, posicion: "MD", foto: "img/jugadores/resto1/jair_castillo.png" },
  { nombre: "Josy Pérez", edad: 26, media: 60, posicion: "MD"},
  { nombre: "Charly V.",  edad: 21, media: 59, posicion: "MO"},
  { nombre: "F.Cantilo",  edad: 28, media: 63, posicion: "MD", foto: "img/jugadores/resto1/fabian_cantillo.png" },
  { nombre: "Misael M.",  edad: 28, media: 65, posicion: "DC", foto: "img/jugadores/resto1/misael.png" },
  { nombre: "J.Muñoz",    edad: 24, media: 62, posicion: "ED"},
  { nombre: "S.Aponza",   edad: 20, media: 59, posicion: "EI"},
  { nombre: "F.Fiorelli", edad: 21, media: 62, posicion: "DC", nacionalidad: "uruguay" }
],

//RESTO2
"Inter Bogotá": [
  { nombre: "W.Fariñez",     edad: 28, media: 67, posicion: "PO", foto: "img/jugadores/resto2/farinez.png", nacionalidad: "venezuela" },
  { nombre: "Y.Gomez",       edad: 28, media: 66, posicion: "LI", foto: "img/jugadores/resto2/yulian.png" },
  { nombre: "A.Irazoque",    edad: 26, media: 66, posicion: "DFC", foto: "img/jugadores/resto2/irazoque.png" },
  { nombre: "C.Vivas",       edad: 24, media: 67, posicion: "DFC", foto: "img/jugadores/resto2/vivas.png", nacionalidad: "venezuela" },
  { nombre: "Joan C.",       edad: 29, media: 67, posicion: "LD", foto: "img/jugadores/resto2/joan_castro.png" },
  { nombre: "Larry V.",      edad: 33, media: 69, posicion: "MD", foto: "img/jugadores/resto2/larry.png" },
  { nombre: "Dannovi Q.",    edad: 25, media: 67, posicion: "MD", foto: "img/jugadores/resto2/dannovi.png" },
  { nombre: "F.Bone",        edad: 30, media: 68, posicion: "MO", foto: "img/jugadores/resto2/bone.png", nacionalidad: "uruguay" },
  { nombre: "J.Caballero",   edad: 28, media: 66, posicion: "EI", foto: "img/jugadores/resto2/caballero.png" },
  { nombre: "F.Sanguinetti", edad: 25, media: 67, posicion: "DC", foto: "img/jugadores/resto2/sanguinetti.png", nacionalidad: "uruguay" },
  { nombre: "S.Girado",      edad: 21, media: 65, posicion: "ED", foto: "img/jugadores/resto2/girado.png" },

  { nombre: "K.Cataño",    edad: 23, media: 66, posicion: "PO", foto: "img/jugadores/resto2/kevin_catano.png" },
  { nombre: "M.Rodas",     edad: 28, media: 65, posicion: "DFC", foto: "img/jugadores/resto2/rodas.png" },
  { nombre: "R.Julio",     edad: 21, media: 64, posicion: "LD"},
  { nombre: "M.Pernia",    edad: 25, media: 65, posicion: "LI", foto: "img/jugadores/resto2/pernia.png", nacionalidad: "venezuela" },
  { nombre: "R.Manjarrez", edad: 26, media: 65, posicion: "MO", foto: "img/jugadores/resto2/manjarrez.png" },
  { nombre: "Dewar V.", edad: 25, media: 62, posicion: "MD"},
  { nombre: "Fabian C.",   edad: 23, media: 64, posicion: "ED" },
  { nombre: "D.Duarte",    edad: 24, media: 66, posicion: "DC", foto: "img/jugadores/resto2/duarte.png", nacionalidad: "paraguay" },
  { nombre: "Y.Garces",    edad: 20, media: 64, posicion: "DC", foto: "img/jugadores/resto2/papula.png" },
  { nombre: "C.Dajome",    edad: 32, media: 67, posicion: "EI", foto: "img/jugadores/resto2/dajome.png" },

  { nombre: "Stalin Motta", edad: 18, media: 77, posicion: "MD", foto: "img/jugadores/LY/motta.png", leyenda: true, premium: true }
],

"Águilas": [
  { nombre: "J.Soto",      edad: 32, media: 66, posicion: "PO", foto: "img/jugadores/resto2/soto.png" },
  { nombre: "Javier M.",   edad: 21, media: 65, posicion: "LI", foto: "img/jugadores/resto2/mena.png" },
  { nombre: "A.Guardia",   edad: 36, media: 64, posicion: "DFC", foto: "img/jugadores/resto2/guardia.png" },
  { nombre: "J.Ontaneda",  edad: 30, media: 65, posicion: "DFC", foto: "img/jugadores/resto2/ontaneda.png", nacionalidad: "ecuador" },
  { nombre: "Dylan L.",    edad: 24, media: 65, posicion: "LD",},
  { nombre: "F.Lozano",    edad: 32, media: 67, posicion: "MD", foto: "img/jugadores/resto2/lozano.png" },
  { nombre: "J.Avalo",     edad: 24, media: 63, posicion: "MD"},
  { nombre: "A.Ricaurte",  edad: 34, media: 67, posicion: "MO", foto: "img/jugadores/resto2/ricaurte.png" },
  { nombre: "J.Noguera",   edad: 24, media: 65, posicion: "EI", foto: "img/jugadores/resto2/noguera.png", nacionalidad: "paraguay" },
  { nombre: "Antony V.",   edad: 23, media: 65, posicion: "DC", foto: "img/jugadores/resto2/anthony.png" },
  { nombre: "E.Arizalas",  edad: 24, media: 65, posicion: "ED", foto: "img/jugadores/resto2/eduar.png" },

  { nombre: "H.Arango",    edad: 24, media: 60, posicion: "PO"},
  { nombre: "J.Garcia",    edad: 37, media: 62, posicion: "DFC"},
  { nombre: "S.Rodriguez", edad: 25, media: 64, posicion: "DFC", foto: "img/jugadores/resto2/sebastian_rodri.png"},
  { nombre: "N.Lara",      edad: 23, media: 63, posicion: "DFC"},
  { nombre: "J.Roa",       edad: 31, media: 65, posicion: "MD", foto: "img/jugadores/resto2/juan_roa.png" },
  { nombre: "Royner B.",   edad: 21, media: 64, posicion: "MO", foto: "img/jugadores/resto2/royner.png" },
  { nombre: "Ivan Rojas",  edad: 28, media: 66, posicion: "MD", foto: "img/jugadores/resto2/rojas.png" },
  { nombre: "R.Marquez",   edad: 28, media: 64, posicion: "DC", foto: "img/jugadores/resto2/caballo.png"},
  { nombre: "M.Ramirez",   edad: 27, media: 65, posicion: "EI", foto: "img/jugadores/resto2/matias.png", nacionalidad: "argentina"},
  { nombre: "A.Carreño",   edad: 22, media: 65, posicion: "DC", foto: "img/jugadores/resto2/carreno.png" },
  { nombre: "J.Melendez",  edad: 24, media: 65, posicion: "ED", foto: "img/jugadores/resto2/melendez.png" },
  { nombre: "F.Charales",  edad: 22, media: 66, posicion: "ED"},

  { nombre: "L.A. Paez",   edad: 18, media: 77, posicion: "DC", foto: "img/jugadores/LY/paez.png", leyenda: true, premium: true }
],

"Fortaleza": [
  { nombre: "W.Barlasina", edad: 28, media: 64, posicion: "PO", foto: "img/jugadores/resto2/barlasina.png", nacionalidad: "argentina" },
  { nombre: "J.C. Castillo", edad: 23, media: 63, posicion: "LI", foto: "img/jugadores/resto2/juan_castillo.png" },
  { nombre: "Y.Diaz", edad: 29, media: 65, posicion: "DFC", foto: "img/jugadores/resto2/yesid.png" },
  { nombre: "D.Pisciotti", edad: 24, media: 65, posicion: "DFC", foto: "img/jugadores/resto2/pisciotti.png" },
  { nombre: "J.Marulanda", edad: 30, media: 66, posicion: "LD", foto: "img/jugadores/resto2/marulanda.png" },
  { nombre: "Leo Pico", edad: 34, media: 67, posicion: "MD", foto: "img/jugadores/resto2/pico.png" },
  { nombre: "S.Navarro", edad: 26, media: 65, posicion: "MD", foto: "img/jugadores/resto2/navarro.png" },
  { nombre: "J.Velasquez", edad: 31, media: 64, posicion: "MO", foto: "img/jugadores/resto2/velasquez.png" },
  { nombre: "Richardson R.", edad: 20, media: 63, posicion: "MO", foto: "img/jugadores/resto2/rivas.png"  },
  { nombre: "Jhonier B.", edad: 25, media: 64, posicion: "DC", foto: "img/jugadores/resto2/jhonier_blanco.png" },
  { nombre: "Teun Wilke", edad: 24, media: 63, posicion: "DC", foto: "img/jugadores/resto2/wilke.png", nacionalidad: "mexico" },

  { nombre: "C.Santander", edad: 22, media: 64, posicion: "PO", foto: "img/jugadores/resto2/santander.png" },
  { nombre: "J.Balanta", edad: 28, media: 64, posicion: "DFC", foto: "img/jugadores/resto2/jhon_balanta.png" },
  { nombre: "A.Copete", edad: 25, media: 64, posicion: "DFC" , foto: "img/jugadores/resto2/copete.png", nacionalidad: "ecuador" },
  { nombre: "J.Cajares", edad: 23, media: 63, posicion: "LD", foto: "img/jugadores/resto2/cajares.png" },
  { nombre: "K.Balanta", edad: 22, media: 63, posicion: "MD", foto: "img/jugadores/resto2/kevin_balanta.png" },
  { nombre: "S.Ramirez", edad: 20, media: 60, posicion: "MD"},
  { nombre: "A.Batioja", edad: 20, media: 61, posicion: "EI"},
  { nombre: "S.Herrera", edad: 31, media: 62, posicion: "DC", foto: "img/jugadores/resto2/herrera.png" },
  { nombre: "F.Pulicastro", edad: 26, media: 63, posicion: "DC", nacionalidad: "argentina" },
  { nombre: "J.Salas", edad: 22, media: 64, posicion: "DC" },
  { nombre: "Italo M.", edad: 27, media: 62, posicion: "DC", foto: "img/jugadores/resto2/italo.png" }
],

//RESTO3
"Llaneros": [
  { nombre: "R.Romaña", edad: 29, media: 63, posicion: "PO", foto: "img/jugadores/resto3/romana.png" },
  { nombre: "J.Medranda", edad: 32, media: 63, posicion: "LI", foto: "img/jugadores/resto3/medranda.png" },
  { nombre: "F.Meza", edad: 34, media: 66, posicion: "DFC", foto: "img/jugadores/resto3/meza.png" },
  { nombre: "A.Moralez", edad: 25, media: 65, posicion: "DFC", foto: "img/jugadores/resto3/moralez.png" },
  { nombre: "J.Pertuz", edad: 21, media: 64, posicion: "LD", foto: "img/jugadores/resto3/pertuz.png" },
  { nombre: "J.Castilla", edad: 22, media: 64, posicion: "MD", foto: "img/jugadores/resto3/castilla.png" },
  { nombre: "Neyder O.", edad: 23, media: 65, posicion: "MD", foto: "img/jugadores/resto3/neyder.png"},
  { nombre: "K.Osorio", edad: 32, media: 65, posicion: "MO", foto: "img/jugadores/resto3/kelvin_osorio.png" },
  { nombre: "D.Mantilla", edad: 29, media: 65, posicion: "EI"},
  { nombre: "C.Barreiro", edad: 24, media: 65, posicion: "DC", foto: "img/jugadores/resto3/barreiro.png" },
  { nombre: "J.Vasquez", edad: 31, media: 67, posicion: "ED", foto: "img/jugadores/resto3/jhon_vasquez.png" },

  { nombre: "J.Loaiza", edad: 23, media: 60, posicion: "PO"},
  { nombre: "Dennys Q.", edad: 29, media: 63, posicion: "DFC", foto: "img/jugadores/resto3/dennys.png", nacionalidad: "ecuador" },
  { nombre: "Howell M.", edad: 25, media: 63, posicion: "DFC", foto: "img/jugadores/resto3/howell.png" },
  { nombre: "Jhojan E.", edad: 26, media: 63, posicion: "LI", foto: "img/jugadores/resto3/jhojan.png"},
  { nombre: "L.Riascos", edad: 26, media: 65, posicion: "LD"},
  { nombre: "D.Quiñones", edad: 27, media: 64, posicion: "LD"},
  { nombre: "E.Restrepo", edad: 27, media: 63, posicion: "MD"},
  { nombre: "M.Sierra", edad: 31, media: 65, posicion: "MD"},
  { nombre: "J.J. Ramirez", edad: 24, media: 65, posicion: "MO", foto: "img/jugadores/resto3/chocolo.png" },
  { nombre: "L.Miranda", edad: 28, media: 65, posicion: "ED", foto: "img/jugadores/resto3/luis_miranda.png" },
  { nombre: "Joel C.", edad: 27, media: 65, posicion: "EI", foto: "img/jugadores/resto3/joel_contreras.png" },
  { nombre: "F.Castañeda", edad: 32, media: 65, posicion: "EI", foto: "img/jugadores/resto3/castaneda.png" },
  { nombre: "L.Marimon", edad: 22, media: 62, posicion: "DC"},
  { nombre: "Yorleys M.", edad: 35, media: 65, posicion: "DC", foto: "img/jugadores/resto3/yorleys.png" },

  { nombre: "J.Muñoz", edad: 18, media: 77, posicion: "DFC", foto: "img/jugadores/LY/munoz.png", leyenda: true, premium: true }
],

"B.Chico": [
  { nombre: "D.Agudelo", edad: 29, media: 62, posicion: "PO", foto: "img/jugadores/resto3/agudelo.png" },
  { nombre: "C.Blanco", edad: 27, media: 63, posicion: "LI", foto: "img/jugadores/resto3/blanco.png"},
  { nombre: "S.Palma", edad: 26, media: 61, posicion: "DFC", foto: "img/jugadores/resto3/palma.png" },
  { nombre: "J.Mena", edad: 37, media: 67, posicion: "DFC", foto: "img/jugadores/resto3/mena.png" },
  { nombre: "J.Quiceno", edad: 21, media: 63, posicion: "DFC", foto: "img/jugadores/resto3/quiceno.png" },
  { nombre: "Sander N.", edad: 23, media: 63, posicion: "LD", foto: "img/jugadores/resto3/sander.png"},
  { nombre: "Delio R.", edad: 25, media: 65, posicion: "MD", foto: "img/jugadores/resto3/delio.png" },
  { nombre: "S.Salazar", edad: 30, media: 62, posicion: "MD", foto: "img/jugadores/resto3/salazar.png" },
  { nombre: "J.C. Diaz", edad: 24, media: 63, posicion: "MD", foto: "img/jugadores/resto3/juan_diaz.png" },
  { nombre: "F.Cifuentes", edad: 24, media: 63, posicion: "DC", foto: "img/jugadores/resto3/cifuentes.png"},
  { nombre: "I.Camargo", edad: 26, media: 65, posicion: "DC", foto: "img/jugadores/resto3/camargo.png" },

  { nombre: "D.Quintero", edad: 28, media: 62, posicion: "PO", foto: "img/jugadores/resto3/david_quintero.png" },
  { nombre: "R.Caicedo", edad: 32, media: 62, posicion: "PO"},
  { nombre: "Arlen B.", edad: 26, media: 61, posicion: "DFC"},
  { nombre: "D.Polanco", edad: 27, media: 64, posicion: "DFC", foto: "img/jugadores/resto3/polanco.png" },
  { nombre: "J.Alomia", edad: 27, media: 62, posicion: "DFC", foto: "img/jugadores/resto3/alomia.png" },
  { nombre: "J.Palacios", edad: 30, media: 63, posicion: "MD", foto: "img/jugadores/resto3/junior_palacios.png"},
  { nombre: "A.Aedo", edad: 22, media: 62, posicion: "MD"},
  { nombre: "Oscar C.", edad: 20, media: 57, posicion: "MO"},
  { nombre: "Y.Cabrera", edad: 35, media: 67, posicion: "MO", foto: "img/jugadores/resto3/yesus.png" },
  { nombre: "J.Pimentel", edad: 24, media: 59, posicion: "EI", foto: "img/jugadores/resto3/pimentel.png" },
  { nombre: "J.Peñaloza", edad: 26, media: 63, posicion: "ED" },
  { nombre: "J.Romaña", edad: 20, media: 58, posicion: "EI"},

  { nombre: "M.Caneo", edad: 18, media: 78, posicion: "MO", foto: "img/jugadores/LY/caneo.png", nacionalidad: "argentina", leyenda: true, premium: true }
],

//RESTO4
"Jaguares": [
  { nombre: "Frankin M.", edad: 27, media: 64, posicion: "PO", foto: "img/jugadores/resto4/franklin.png" },
  { nombre: "N.Giraldo", edad: 33, media: 63, posicion: "LI"},
  { nombre: "C.Henao", edad: 37, media: 65, posicion: "DFC", foto: "img/jugadores/resto4/henao.png" },
  { nombre: "J.Lovera", edad: 21, media: 62, posicion: "DFC" },
  { nombre: "E.Martinez", edad: 22, media: 62, posicion: "LD", foto: "img/jugadores/resto4/edwin_martinez.png" },
  { nombre: "Roycer C.", edad: 31, media: 63, posicion: "MD", foto: "img/jugadores/resto4/roycer.png" },
  { nombre: "J.Hinestroza", edad: 24, media: 63, posicion: "MD", foto: "img/jugadores/resto4/hinestroza.png" },
  { nombre: "C. Jopito A.", edad: 33, media: 65, posicion: "MO", foto: "img/jugadores/resto4/jopito.png", nacionalidad: "argentina" },
  { nombre: "S.Cubides", edad: 25, media: 62, posicion: "DC", foto: "img/jugadores/resto4/cubides.png" },
  { nombre: "A.Renteria", edad: 33, media: 67, posicion: "DC", foto: "img/jugadores/resto4/topo.png" },
  { nombre: "W. de la Rosa", edad: 33, media: 63, posicion: "ED", foto: "img/jugadores/resto4/wilfrido.png" },

  { nombre: "D.Martinez", edad: 36, media: 63, posicion: "PO", foto: "img/jugadores/resto4/diego_martinez.png" },
  { nombre: "J.Malagon", edad: 33, media: 63, posicion: "DFC", foto: "img/jugadores/resto4/malagon.png"  },
  { nombre: "L.Jimenez", edad: 28, media: 62, posicion: "LD"},
  { nombre: "A.Alfonzo", edad: 21, media: 61, posicion: "LD"},
  { nombre: "C.Franco", edad: 24, media: 63, posicion: "LD", foto: "img/jugadores/resto4/franco.png"},
  { nombre: "Y.Mosquera", edad: 31, media: 63, posicion: "MD"},
  { nombre: "R.Bustamante", edad: 26, media: 65, posicion: "MD", foto: "img/jugadores/resto4/bustamante.png" },
  { nombre: "J.Beltran", edad: 26, media: 64, posicion: "MO", foto: "img/jugadores/resto4/beltran.png" },
  { nombre: "Duvan R.", edad: 30, media: 63, posicion: "ED"},
  { nombre: "J.Maza", edad: 31, media: 63, posicion: "EI", foto: "img/jugadores/resto4/jader_maza.png" },
  { nombre: "Faber Gil", edad: 31, media: 64, posicion: "ED", foto: "img/jugadores/resto4/gil.png" },
  { nombre: "Darwin L.", edad: 34, media: 63, posicion: "DC", foto: "img/jugadores/resto4/darwin_lopez.png" },
  { nombre: "J.Mejia", edad: 26, media: 63, posicion: "DC", foto: "img/jugadores/resto4/johar.png" },

  { nombre: "Pablo Rojas", edad: 18, media: 76, posicion: "DC", foto: "img/jugadores/LY/rojas.png", leyenda: true, premium: true }
],

"Cucuta": [
  { nombre: "F.Abadia", edad: 28, media: 63, posicion: "PO", foto: "img/jugadores/resto4/abadia.png", nacionalidad: "argentina" },
  { nombre: "M.Duarte", edad: 34, media: 63, posicion: "LI", foto: "img/jugadores/resto4/duarte.png" },
  { nombre: "H.Lopes", edad: 35, media: 65, posicion: "DFC", foto: "img/jugadores/resto4/lopes.png", nacionalidad: "argentina" },
  { nombre: "D.Calcaterra", edad: 25, media: 65, posicion: "DFC", foto: "img/jugadores/resto4/calcaterra.png", nacionalidad: "argentina" },
  { nombre: "J.Abonia", edad: 26, media: 64, posicion: "LD", foto: "img/jugadores/resto4/abonia.png" },
  { nombre: "V.Mejia", edad: 33, media: 65, posicion: "MD", foto: "img/jugadores/resto4/mejia.png" },
  { nombre: "S.Tamara", edad: 30, media: 65, posicion: "MD", foto: "img/jugadores/resto4/tamara.png" },
  { nombre: "L.Berdugo", edad: 24, media: 66, posicion: "MO", foto: "img/jugadores/resto4/berdugo.png" },
  { nombre: "L.Rios", edad: 28, media: 66, posicion: "MO", foto: "img/jugadores/resto4/lucas_rios.png", nacionalidad: "argentina" },
  { nombre: "J.Peralta", edad: 21, media: 65, posicion: "DC", foto: "img/jugadores/resto4/peralta.png" },
  { nombre: "G.Torres", edad: 30, media: 65, posicion: "ED", foto: "img/jugadores/resto4/gustavo_torres.png" },

  { nombre: "J.Ramirez", edad: 29, media: 63, posicion: "PO"},
  { nombre: "B.Montaño", edad: 23, media: 63, posicion: "DFC", foto: "img/jugadores/resto4/montano.png" },
  { nombre: "A.Quiñones", edad: 22, media: 64, posicion: "DFC", foto: "img/jugadores/resto4/jhon_quinones.png" },
  { nombre: "K.A. Londoño", edad: 26, media: 63, posicion: "MD", foto: "img/jugadores/resto4/londono.png" },
  { nombre: "J.Ceballos", edad: 27, media: 64, posicion: "MD", foto: "img/jugadores/resto4/ceballos.png" },
  { nombre: "Samir Mayo", edad: 23, media: 63, posicion: "MD"},
  { nombre: "C.Renteria", edad: 31, media: 63, posicion: "MD", foto: "img/jugadores/resto4/neneco.png"},
  { nombre: "J.Agudelo", edad: 33, media: 62, posicion: "DC", foto: "img/jugadores/resto4/agudelo.png" },
  { nombre: "M.Carabali", edad: 23, media: 63, posicion: "ED", foto: "img/jugadores/resto4/marlon_carabali.png"},

  { nombre: "Blas Perez", edad: 18, media: 78, posicion: "DC", foto: "img/jugadores/LY/blas.png", leyenda: true, premium: true, nacionalidad: "panama" }
],

//RESTO5
"Envigado": [
  { nombre: "A.Tovar", edad: 20, media: 62, posicion: "PO", foto: "img/jugadores/resto5/tovar.png" },
  { nombre: "E.Londoño", edad: 20, media: 58, posicion: "LI" },
  { nombre: "J.Gamboa", edad: 25, media: 62, posicion: "DFC", foto: "img/jugadores/resto5/gamboa.png" },
  { nombre: "Didier P.", edad: 22, media: 62, posicion: "DFC", foto: "img/jugadores/resto5/didier_palacios.png"},
  { nombre: "G.Cuervo", edad: 24, media: 63, posicion: "LD", foto: "img/jugadores/resto5/gendry.png" },
  { nombre: "Julian P.", edad: 22, media: 62, posicion: "MD", foto: "img/jugadores/resto5/julian_palacios.png" },
  { nombre: "W.Hurtado", edad: 22, media: 62, posicion: "MD" },
  { nombre: "C.Nieva", edad: 23, media: 62, posicion: "MO" },
  { nombre: "Dairon V.", edad: 26, media: 62, posicion: "EI", foto: "img/jugadores/resto5/dairon.png" },
  { nombre: "Stiwart A.", edad: 27, media: 62, posicion: "DC", foto: "img/jugadores/resto5/stiwart.png" },
  { nombre: "J.Hernandez", edad: 33, media: 62, posicion: "DC", foto: "img/jugadores/resto5/jesus.png", nacionalidad: "venezuela" },
  
  { nombre: "J.Mora", edad: 29, media: 62, posicion: "PO", foto: "img/jugadores/resto5/mora.png" },
  { nombre: "S.Noreña", edad: 27, media: 61, posicion: "DFC", foto: "img/jugadores/resto5/norena.png" },
  { nombre: "J.Gomez", edad: 30, media: 62, posicion: "DFC", foto: "img/jugadores/resto5/jefferson_gomez.png" },
  { nombre: "J.J. Cataño", edad: 17, media: 57, posicion: "MD" },
  { nombre: "Frey Berrio", edad: 19, media: 61, posicion: "MO"},
  { nombre: "R.España", edad: 22, media: 61, posicion: "EI"},
  { nombre: "Joao R.", edad: 30, media: 65, posicion: "EI", foto: "img/jugadores/resto5/joao_rodriguez.png" },
  { nombre: "D.Dawson", edad: 20, media: 58, posicion: "ED", nacionalidad: "panama" },
  { nombre: "Angelo R.", edad: 37, media: 65, posicion: "DC", foto: "img/jugadores/resto5/angello.png" },
  { nombre: "M.Marulanda", edad: 18, media: 61, posicion: "DC" },
  { nombre: "N.Morantes", edad: 18, media: 76, posicion: "MO", foto: "img/jugadores/LY/morantes.png", leyenda: true, premium: true }
],

"Real Cartagena": [
  { nombre: "G.Gomez", edad: 30, media: 64, posicion: "PO", foto: "img/jugadores/resto5/gomez.png" },
  { nombre: "C.de las Salas", edad: 28, media: 66, posicion: "LI", foto: "img/jugadores/resto5/cdls.png" },
  { nombre: "G.Tegüe", edad: 26, media: 63, posicion: "DFC", foto: "img/jugadores/resto5/tegue.png" },
  { nombre: "R.Lora", edad: 29, media: 64, posicion: "DFC", foto: "img/jugadores/resto5/lora.png" },
  { nombre: "C.Graciano", edad: 23, media: 66, posicion: "LD", foto: "img/jugadores/resto5/graciano.png" },
  { nombre: "Edison L.", edad: 26, media: 66, posicion: "MD", foto: "img/jugadores/resto5/edison_lopez.png" },
  { nombre: "D.Pino", edad: 30, media: 63, posicion: "MD", foto: "img/jugadores/resto5/pino.png" },
  { nombre: "Jarlan B.", edad: 30, media: 68, posicion: "MO", foto: "img/jugadores/resto5/jarlan.png" },
  { nombre: "J.Aleman", edad: 24, media: 63, posicion: "EI" },
  { nombre: "F.Montero", edad: 39, media: 71, posicion: "DC", foto: "img/jugadores/resto5/montero.png" },
  { nombre: "A.Melendez", edad: 29, media: 65, posicion: "ED", foto: "img/jugadores/resto5/melendez.png" },

  { nombre: "A.Montes", edad: 26, media: 62, posicion: "PO", foto: "img/jugadores/resto5/montes.png" },
  { nombre: "R.Fontalvo", edad: 27, media: 62, posicion: "PO"},
  { nombre: "M.Balanta", edad: 22, media: 62, posicion: "DFC" },
  { nombre: "A.Escobar", edad: 29, media: 64, posicion: "LI", foto: "img/jugadores/resto5/escobar.png" },
  { nombre: "J.D. Rodriguez", edad: 33, media: 65, posicion: "MD", foto: "img/jugadores/resto5/juandarodri.png" },
  { nombre: "J.Solarte", edad: 25, media: 62, posicion: "MD" },
  { nombre: "J.Pineda", edad: 28, media: 66, posicion: "MD"},
  { nombre: "J.P. Gallego", edad: 25, media: 65, posicion: "MO", foto: "img/jugadores/resto5/gallego.png" },
  { nombre: "Diego C.", edad: 26, media: 65, posicion: "EI", foto: "img/jugadores/resto5/diego_castillo.png" },
  { nombre: "L.Yanes", edad: 19, media: 61, posicion: "EI" },
  { nombre: "M.Manotas", edad: 31, media: 68, posicion: "DC", foto: "img/jugadores/resto5/manotas.png" },

  { nombre: "J.Najera", edad: 18, media: 76, posicion: "DC", foto: "img/jugadores/LY/najera.png", leyenda: true, premium: true }
],

"Patriotas": [
  { nombre: "J.Amaya", edad: 23, media: 59, posicion: "PO" },
  { nombre: "L.Renteria", edad: 20, media: 61, posicion: "LI", foto: "img/jugadores/resto5/renteria.png" },
  { nombre: "A.Carabali", edad: 22, media: 60, posicion: "DFC" },
  { nombre: "J.Hurtado", edad: 28, media: 63, posicion: "DFC", foto: "img/jugadores/resto5/hurtado.png" },
  { nombre: "A.Porras", edad: 26, media: 62, posicion: "LD", foto: "img/jugadores/resto5/porras.png"},
  { nombre: "M.Figueroa", edad: 28, media: 62, posicion: "MD", foto: "img/jugadores/resto5/freyn.png", nacionalidad: "venezuela" },
  { nombre: "T.Molina", edad: 21, media: 63, posicion: "MD", foto: "img/jugadores/resto5/molina.png" },
  { nombre: "K.Alvarez", edad: 21, media: 65, posicion: "MO", foto: "img/jugadores/resto5/kevin_alvarez.png" },
  { nombre: "J.Campaña", edad: 23, media: 63, posicion: "EI", foto: "img/jugadores/resto5/campana.png" },
  { nombre: "M.Nike", edad: 29, media: 62, posicion: "DC", foto: "img/jugadores/resto5/nike.png" },
  { nombre: "J.Montes", edad: 21, media: 61, posicion: "ED" },
  
  { nombre: "Fernando T.", edad: 21, media: 59, posicion: "MD" },
  { nombre: "A.Mora", edad: 18, media: 59, posicion: "MO" },
  { nombre: "C.Salguero", edad: 29, media: 63, posicion: "ED", foto: "img/jugadores/resto5/salguero.png"},
  { nombre: "C.Copete", edad: 26, media: 62, posicion: "DC", foto: "img/jugadores/resto5/copete.png" },
  { nombre: "J.E. Sanchez", edad: 19, media: 58, posicion: "DC" },

],

//RESTO6
"U.Magdalena": [
  { nombre: "V.Cabezas", edad: 28, media: 64, posicion: "PO", foto: "img/jugadores/resto6/cabezas.png" },
  { nombre: "J.J. Vazquez", edad: 26, media: 62, posicion: "LI", foto: "img/jugadores/resto6/jjvasquez.png" },
  { nombre: "R.Delvalle", edad: 25, media: 64, posicion: "DFC", foto: "img/jugadores/resto6/delvalle.png", nacionalidad: "paraguay" },
  { nombre: "F.Molina", edad: 22, media: 62, posicion: "DFC", foto: "img/jugadores/resto6/freddy_molina.png", nacionalidad: "venezuela" },
  { nombre: "D.Mera", edad: 26, media: 63, posicion: "LD", foto: "img/jugadores/resto6/mera.png" },
  { nombre: "Y.Congo", edad: 28, media: 63, posicion: "MD", foto: "img/jugadores/resto6/congo.png" },
  { nombre: "K.Salazar", edad: 28, media: 65, posicion: "MD", foto: "img/jugadores/resto6/kevin_salazar.png" },
  { nombre: "J.Mercado", edad: 22, media: 63, posicion: "MO", foto: "img/jugadores/resto6/mercado.png" },
  { nombre: "G.Arrieta", edad: 20, media: 58, posicion: "EI" },
  { nombre: "C.Iguaran", edad: 20, media: 64, posicion: "DC", foto: "img/jugadores/resto6/iguaran.png" },
  { nombre: "J.Lerma", edad: 23, media: 63, posicion: "ED", foto: "img/jugadores/resto6/lerma.png" },

  { nombre: "M.Tasso", edad: 25, media: 62, posicion: "PO", foto: "img/jugadores/resto6/tasso.png", nacionalidad: "argentina" },
  { nombre: "D.Mojica", edad: 19, media: 58, posicion: "PO" },
  { nombre: "J.Peñaloza", edad: 17, media: 61, posicion: "DFC", foto: "img/jugadores/resto6/penaloza.png" },
  { nombre: "Dilan O.", edad: 22, media: 61, posicion: "DFC"},
  { nombre: "J.D. Giraldo", edad: 28, media: 62, posicion: "MD", foto: "img/jugadores/resto6/giraldo.png" },
  { nombre: "F.Mosquera", edad: 31, media: 63, posicion: "MD", foto: "img/jugadores/resto6/fabian.png" },
  { nombre: "J.Farias", edad: 22, media: 63, posicion: "DC", foto: "img/jugadores/resto6/teclita.png", nacionalidad: "argentina" },
  { nombre: "Kleber Diaz", edad: 22, media: 58, posicion: "DC"},
  { nombre: "J.Pimienta", edad: 28, media: 62, posicion: "DC" },

],

"Inter Palmira": [
  { nombre: "W.Cuesta", edad: 33, media: 64, posicion: "PO", foto: "img/jugadores/resto6/cuesta.png" },
  { nombre: "A.Alvarez", edad: 27, media: 64, posicion: "LI", foto: "img/jugadores/resto6/andres_alvarez.png" },
  { nombre: "A.Mejia", edad: 29, media: 63, posicion: "DFC", foto: "img/jugadores/resto6/alejo_mejia.png" },
  { nombre: "M.Caicedo", edad: 22, media: 63, posicion: "DFC", foto: "img/jugadores/resto6/manuel.png" },
  { nombre: "J.C. Angulo", edad: 37, media: 63, posicion: "LD", foto: "img/jugadores/resto6/angulo.png" },
  { nombre: "H.Suarez", edad: 32, media: 65, posicion: "MD", foto: "img/jugadores/resto6/harlin.png" },
  { nombre: "J.Velez", edad: 23, media: 63, posicion: "MD", foto: "img/jugadores/resto6/velez.png" },
  { nombre: "Kener G.", edad: 20, media: 65, posicion: "MO", foto: "img/jugadores/resto6/kener.png" },
  { nombre: "J.E. Mosquera", edad: 36, media: 63, posicion: "EI", foto: "img/jugadores/resto6/jhon_mosquera.png" },
  { nombre: "R.Brochero", edad: 26, media: 64, posicion: "DC", foto: "img/jugadores/resto6/brochero.png" },
  { nombre: "D.Orozco", edad: 30, media: 65, posicion: "ED", foto: "img/jugadores/resto6/david_orozco.png" },

  { nombre: "A.Perez", edad: 27, media: 62, posicion: "PO", foto: "img/jugadores/resto6/andres_perez.png" },
  { nombre: "C.Ramirez", edad: 38, media: 63, posicion: "DFC"},
  { nombre: "Y.Ariza", edad: 20, media: 61, posicion: "DFC" },
  { nombre: "Eli Mina", edad: 26, media: 63, posicion: "DFC", foto: "img/jugadores/resto6/elimina.png" },
  { nombre: "C.Franco", edad: 22, media: 63, posicion: "MD", foto: "img/jugadores/resto6/franco.png" },
  { nombre: "K.Padilla", edad: 25, media: 63, posicion: "MD"},
  { nombre: "Jown C.", edad: 31, media: 63, posicion: "MO"},
  { nombre: "Fabian C.", edad: 34, media: 64, posicion: "EI", foto: "img/jugadores/resto6/fabian_castillo.png" },
  { nombre: "Jaider M.", edad: 22, media: 63, posicion: "EI", foto: "img/jugadores/resto6/jaider.png" },
  { nombre: "Rivaldo C.", edad: 26, media: 60, posicion: "DC" }
],

"Quindio": [
  { nombre: "Joel Silva", edad: 37, media: 62, posicion: "PO", foto: "img/jugadores/resto6/joel_silva.png", nacionalidad: "paraguay" },
  { nombre: "M.Castaño", edad: 32, media: 63, posicion: "LI", foto: "img/jugadores/resto6/castano.png" },
  { nombre: "Yosimarc T.", edad: 27, media: 64, posicion: "MD", foto: "img/jugadores/resto6/yosimarc.png" },
  { nombre: "J.E. Ocampo", edad: 27, media: 62, posicion: "DFC"},
  { nombre: "J.Sandoval", edad: 24, media: 63, posicion: "LD" },
  { nombre: "S.Orozco", edad: 30, media: 64, posicion: "MD", foto: "img/jugadores/resto6/orozco.png" },
  { nombre: "Felix M.", edad: 20, media: 59, posicion: "MD", foto: "img/jugadores/resto6/felix_mosquera.png" },
  { nombre: "J.Reina", edad: 37, media: 66, posicion: "MO", foto: "img/jugadores/resto6/reina.png" },
  { nombre: "Jhonier V.", edad: 34, media: 63, posicion: "EI", foto: "img/jugadores/resto6/jhonier_viveros.png" },
  { nombre: "Miller B.", edad: 22, media: 62, posicion: "DC", foto: "img/jugadores/resto6/miller.png"},
  { nombre: "J.Lloreda", edad: 31, media: 65, posicion: "DC", foto: "img/jugadores/resto6/lloreda.png" },
  
  { nombre: "M.Jimenez", edad: 30, media: 61, posicion: "PO", foto: "img/jugadores/resto6/jimenez.png" },
  { nombre: "S.Pabon", edad: 30, media: 62, posicion: "PO", foto: "img/jugadores/resto6/pabon.png" },
  { nombre: "Uberney R.", edad: 20, media: 62, posicion: "DFC"},
  { nombre: "S.Roa", edad: 30, media: 62, posicion: "MD", foto: "img/jugadores/resto6/roa.png" },
  { nombre: "A.Tello", edad: 29, media: 63, posicion: "MD"},
  { nombre: "R.Angulo", edad: 25, media: 62, posicion: "EI"},
  { nombre: "A.Carabali", edad: 28, media: 63, posicion: "DC", foto: "img/jugadores/resto6/carabali.png" },
  { nombre: "Alejo Alvarez", edad: 22, media: 59, posicion: "DC" },

],

//RESTO7
"IVC": [
  { nombre: "J.Mendez", edad: 25, media: 62, posicion: "PO", foto: "img/jugadores/resto7/mendez.png" },
  { nombre: "A.Rojas", edad: 20, media: 59, posicion: "LI" },
  { nombre: "Jesus R.", edad: 20, media: 58, posicion: "DFC" },
  { nombre: "Julian R.", edad: 23, media: 62, posicion: "DFC" },
  { nombre: "J.Ampudia", edad: 26, media: 62, posicion: "LD", foto: "img/jugadores/resto7/ampudia.png" },
  { nombre: "Y.Ordoñez", edad: 22, media: 63, posicion: "MO" },
  { nombre: "J.Rubiano", edad: 24, media: 62, posicion: "MO" },
  { nombre: "H.Mena", edad: 26, media: 63, posicion: "EI", foto: "img/jugadores/resto7/hugo_mena.png" },
  { nombre: "L.Farias", edad: 31, media: 63, posicion: "DC", foto: "img/jugadores/resto7/lucas_farias.png", nacionalidad: "argentina" },
  { nombre: "M.Sequeda", edad: 21, media: 62, posicion: "DC" },
  { nombre: "T.Diaz", edad: 20, media: 63, posicion: "ED", foto: "img/jugadores/resto7/tomas_diaz.png"},
  
  { nombre: "L.Mena", edad: 21, media: 62, posicion: "PO"},
  { nombre: "D.Ferrer", edad: 19, media: 58, posicion: "DFC" },
  { nombre: "J.Lozano", edad: 19, media: 58, posicion: "DFC" },
  { nombre: "L.A. Quiñonez", edad: 22, media: 61, posicion: "LI", nacionalidad: "ecuador" },
  { nombre: "Alan G.", edad: 18, media: 59, posicion: "DC" },
  { nombre: "B.Moya", edad: 23, media: 62, posicion: "ED" },

],

"R.Cundinamarca": [
  { nombre: "M.Valencia", edad: 22, media: 59, posicion: "PO", foto: "img/jugadores/resto7/mateo_valencia.png" },
  { nombre: "O.Acosta", edad: 26, media: 63, posicion: "LI", foto: "img/jugadores/resto7/onel.png" },
  { nombre: "B.Suaza", edad: 24, media: 63, posicion: "DFC"},
  { nombre: "Samuel F.", edad: 23, media: 60, posicion: "DFC" },
  { nombre: "Jeronimo R.", edad: 20, media: 59, posicion: "LD" },
  { nombre: "J.D. Hoyos", edad: 21, media: 59, posicion: "MD" },
  { nombre: "A.Cano", edad: 25, media: 62, posicion: "MD"},
  { nombre: "J.Amaya", edad: 20, media: 59, posicion: "MO"},
  { nombre: "Kleiton C.", edad: 22, media: 59, posicion: "DC" },
  { nombre: "J.Jaramillo", edad: 22, media: 61, posicion: "DC" },
  { nombre: "Brayan C.", edad: 24, media: 63, posicion: "ED"},

  { nombre: "James G.", edad: 19, media: 57, posicion: "PO" },
  { nombre: "J.M. Cortes", edad: 22, media: 59, posicion: "LI" },
  { nombre: "C.Negrete", edad: 19, media: 59, posicion: "DC" }
],

"Boca Jrs. Cali": [
  { nombre: "E.Obando", edad: 24, media: 59, posicion: "PO", foto: "img/jugadores/resto7/euler.png" },
  { nombre: "D.Beitar", edad: 18, media: 59, posicion: "LI" },
  { nombre: "K.Hurtado", edad: 21, media: 61, posicion: "DFC" },
  { nombre: "Y.Moran", edad: 23, media: 60, posicion: "DFC"},
  { nombre: "Heiner M.", edad: 21, media: 59, posicion: "LD" },
  { nombre: "L.A. Perez", edad: 23, media: 59, posicion: "MD" },
  { nombre: "H.Ortiz", edad: 22, media: 63, posicion: "MD", foto: "img/jugadores/resto7/harold_ortiz.jpg" },
  { nombre: "W.Arango", edad: 28, media: 64, posicion: "MO"},
  { nombre: "M.Aponza", edad: 20, media: 62, posicion: "EI", foto: "img/jugadores/resto7/michael_aponza.png" },
  { nombre: "J.J. Salcedo", edad: 33, media: 63, posicion: "DC", foto: "img/jugadores/resto7/jjsalcedo.png" },
  { nombre: "P.Urrutia", edad: 27, media: 60, posicion: "ED" },

  { nombre: "S.Hoyos", edad: 21, media: 58, posicion: "PO"},
  { nombre: "H.Angulo", edad: 26, media: 60, posicion: "MD"},
  { nombre: "J.Urresti", edad: 20, media: 60, posicion: "EI" },
  { nombre: "J.C. Cuero", edad: 17, media: 59, posicion: "ED" },
  { nombre: "J.Andrade", edad: 30, media: 62, posicion: "MD"},
  { nombre: "H.Reina", edad: 36, media: 62, posicion: "DC"},
  { nombre: "J.F. Caicedo", edad: 37, media: 63, posicion: "DC"},

],

"Leones": [
  { nombre: "J.Figueroa", edad: 33, media: 63, posicion: "PO", foto: "img/jugadores/resto7/jhon_figueroa.png" },
  { nombre: "J.C. Renteria", edad: 27, media: 60, posicion: "LI"},
  { nombre: "J.J. Parra", edad: 25, media: 60, posicion: "DFC" },
  { nombre: "G.Meneses", edad: 24, media: 63, posicion: "DFC", foto: "img/jugadores/resto7/meneses.png" },
  { nombre: "M.Arboleda", edad: 26, media: 60, posicion: "LD" },
  { nombre: "T.Calle", edad: 19, media: 58, posicion: "MD" },
  { nombre: "D.Villa", edad: 24, media: 63, posicion: "MD", foto: "img/jugadores/resto7/david_villa.png" },
  { nombre: "S.Montoya", edad: 20, media: 59, posicion: "MO" },
  { nombre: "C.Rodriguez", edad: 24, media: 61, posicion: "MO", foto: "img/jugadores/resto7/cristian_rodri.png" },
  { nombre: "K.Peñaloza", edad: 24, media: 62, posicion: "DC" },
  { nombre: "O.Segura", edad: 23, media: 59, posicion: "ED"},

  { nombre: "J.Arboleda", edad: 20, media: 61, posicion: "PO"},
  { nombre: "C.Holguin", edad: 22, media: 59, posicion: "PO"},
  { nombre: "J.D. Bonilla", edad: 20, media: 59, posicion: "DC"}
],

 "Tigres": [
  { nombre: "V.Brid", edad: 25, media: 59, posicion: "PO", foto: "img/jugadores/resto7/brid.png" },
  { nombre: "J.Cano", edad: 27, media: 60, posicion: "LI"},
  { nombre: "O.Preciado", edad: 26, media: 58, posicion: "DFC" },
  { nombre: "A.Lopera", edad: 24, media: 60, posicion: "DFC"},
  { nombre: "A.Cuadros", edad: 26, media: 60, posicion: "MD" },
  { nombre: "S.Villamil", edad: 21, media: 60, posicion: "MD" },
  { nombre: "M.Alvarez", edad: 23, media: 58, posicion: "MO" },
  { nombre: "Yimmer S.", edad: 29, media: 63, posicion: "MO" },
  { nombre: "Jader M.", edad: 20, media: 58, posicion: "ED" },
  { nombre: "O.Aragon", edad: 28, media: 60, posicion: "DC"},
  { nombre: "L.M. Palacios", edad: 21, media: 60, posicion: "ED"},

  { nombre: "K.Lopez", edad: 23, media: 59, posicion: "PO"},
  { nombre: "Kevin M.", edad: 22, media: 58, posicion: "MD" },
  { nombre: "M.A. Cañon", edad: 25, media: 59, posicion: "EI"},
  { nombre: "C.Ibarra", edad: 23, media: 60, posicion: "DC" }
],
  
  "Bogotá": [
  { nombre: "D.Aguilar", edad: 22, media: 59, posicion: "PO"},
  { nombre: "J.C. Moreno", edad: 24, media: 59, posicion: "LI"},
  { nombre: "Malcom P.", edad: 22, media: 60, posicion: "DFC" },
  { nombre: "H.Ramos", edad: 22, media: 61, posicion: "DFC", nacionalidad:"panama" },
  { nombre: "Jafe P.", edad: 21, media: 60, posicion: "MD" },
  { nombre: "J.Sanchez", edad: 23, media: 58, posicion: "MD" },
  { nombre: "K.Castro", edad: 27, media: 60, posicion: "MD" },
  { nombre: "Ray Vanegas", edad: 33, media: 63, posicion: "EI", foto: "img/jugadores/resto7/ray.png" },
  { nombre: "K.Aladesanmi", edad: 27, media: 63, posicion: "DC", foto: "img/jugadores/resto7/aladesanmi.png" },
  { nombre: "Nezareth S.", edad: 19, media: 58, posicion: "DC" },
  { nombre: "B.Cuero", edad: 22, media: 61, posicion: "ED" },

  { nombre: "J.Osorno", edad: 21, media: 57, posicion: "PO" },
  { nombre: "J.Velasco", edad: 21, media: 59, posicion: "MD" },
  { nombre: "H.Sandoval", edad: 24, media: 60, posicion: "ED"},
  { nombre: "S.Perea", edad: 18, media: 57, posicion: "DC" },

],
  
  "Orsomarso": [
  { nombre: "Iker B.", edad: 20, media: 59, posicion: "PO" },
  { nombre: "S.Agamez", edad: 21, media: 59, posicion: "DFC" },
  { nombre: "Nawer V.", edad: 21, media: 59, posicion: "DFC"},
  { nombre: "Deivi B.", edad: 22, media: 62, posicion: "DFC", foto: "img/jugadores/resto7/deivi.png" },
  { nombre: "V.Lasso", edad: 20, media: 58, posicion: "DFC" },
  { nombre: "Samuel G.", edad: 22, media: 58, posicion: "LD" },
  { nombre: "K.A. Gomez", edad: 30, media: 61, posicion: "MD" },
  { nombre: "J.Muñoz", edad: 22, media: 59, posicion: "MO" },
  { nombre: "J.Zarante", edad: 19, media: 59, posicion: "MD" },
  { nombre: "A.Ruiz", edad: 21, media: 58, posicion: "EI"},
  { nombre: "Bayron C.", edad: 21, media: 60, posicion: "ED" },

  { nombre: "J.Grisales", edad: 21, media: 58, posicion: "PO"},
  { nombre: "J.Salinas", edad: 19, media: 59, posicion: "DFC" },
  { nombre: "J.Hernandez", edad: 17, media: 58, posicion: "MD" }
],

 "Barranquilla": [
  { nombre: "S.Guerra", edad: 25, media: 63, posicion: "PO", foto: "img/jugadores/resto7/guerra.png" },
  { nombre: "J.Cortez", edad: 20, media: 59, posicion: "LI" },
  { nombre: "O.Cassiani", edad: 20, media: 60, posicion: "DFC" },
  { nombre: "A.Licona", edad: 21, media: 58, posicion: "DFC" },
  { nombre: "Yeferson M.", edad: 22, media: 62, posicion: "LD"},
  { nombre: "A.Orozco", edad: 20, media: 60, posicion: "MD" },
  { nombre: "M.Bolivar", edad: 20, media: 60, posicion: "MD" },
  { nombre: "Javier O.", edad: 22, media: 60, posicion: "MO" },
  { nombre: "Yesid G.", edad: 20, media: 58, posicion: "DC" },
  { nombre: "Jhoynner L.", edad: 21, media: 59, posicion: "DC" },
  { nombre: "Darwin T.", edad: 18, media: 59, posicion: "ED" },

  { nombre: "A.Chaverra", edad: 20, media: 57, posicion: "PO" },
  { nombre: "Neymar U.", edad: 22, media: 62, posicion: "LD", foto: "img/jugadores/resto7/neymar.png" },
  { nombre: "Philippe O.", edad: 18, media: 58, posicion: "MO"},
  { nombre: "M.Agamez", edad: 17, media: 60, posicion: "MD"},
  { nombre: "C.Peñate", edad: 21, media: 60, posicion: "MO" },
   { nombre: "S.Borja", edad: 20, media: 59, posicion: "MD" }
],
  
"Atlético FC": [
  { nombre: "J.Munera", edad: 25, media: 60, posicion: "PO", nacionalidad: "españa" },
  { nombre: "J.Veira", edad: 22, media: 59, posicion: "LI", foto: "img/jugadores/resto7/veira.png" },
  { nombre: "F.Villa", edad: 21, media: 61, posicion: "DFC", foto: "img/jugadores/resto7/fabian_villa.png" },
  { nombre: "J.Palacios", edad: 26, media: 60, posicion: "DFC" },
  { nombre: "S.Saavedra", edad: 21, media: 59, posicion: "DFC", nacionalidad: "usa" },
  { nombre: "J.Perdomo", edad: 20, media: 58, posicion: "LD"},
  { nombre: "C.Restrepo", edad: 22, media: 57, posicion: "MD" },
  { nombre: "G.Erazo", edad: 26, media: 61, posicion: "MO", foto: "img/jugadores/resto7/erazo.png" },
  { nombre: "Nicolas H.", edad: 21, media: 62, posicion: "MD"},
  { nombre: "A.Oñate", edad: 22, media: 59, posicion: "DC" },
  { nombre: "Yofer C.", edad: 22, media: 58, posicion: "DC" },

  { nombre: "J.Jaramillo", edad: 26, media: 60, posicion: "PO", foto: "img/jugadores/resto7/jaramillo.png" },

],

"R.Santander": [
  { nombre: "J.Lazaro", edad: 19, media: 56, posicion: "PO" },
  { nombre: "J.Habib", edad: 20, media: 57, posicion: "LI" },
  { nombre: "C.Duran", edad: 21, media: 57, posicion: "DFC" },
  { nombre: "Jordi H.", edad: 20, media: 58, posicion: "DFC" },
  { nombre: "Jorge P.", edad: 19, media: 58, posicion: "MD" },
  { nombre: "L.Rangel", edad: 22, media: 58, posicion: "MD" },
  { nombre: "Breiner R.", edad: 22, media: 57, posicion: "MD" },
  { nombre: "H.Salas", edad: 26, media: 58, posicion: "EI" },
  { nombre: "J.Guillen", edad: 20, media: 58, posicion: "DC" },
  { nombre: "Michell D.", edad: 21, media: 62, posicion: "DC"},
  { nombre: "J.Ararat", edad: 23, media: 58, posicion: "ED" },

  { nombre: "Brandon M.", edad: 20, media: 59, posicion: "DC" },
  { nombre: "A.Segura", edad: 23, media: 57, posicion: "DC" },
  { nombre: "S.Rey", edad: 21, media: 62, posicion: "DC", nacionalidad: "mexico" }
],

"Extranjero":[
   { nombre: "A.Montero", edad: 31, media: 76, posicion: "PO", foto: "img/jugadores/X/montero.png" },
   { nombre: "A.Quintana", edad: 31, media: 73, posicion: "PO" , foto: "img/jugadores/X/quintana.png"},
   { nombre: "J.Moreno", edad: 26, media: 66, posicion: "PO" , foto: "img/jugadores/X/moreno.png"},
   { nombre: "D.Ospina", edad: 37, media: 75, posicion: "PO" , foto: "img/jugadores/D/dospina.png"},
   { nombre: "H.Castillo", edad: 32, media: 70, posicion: "PO" , foto: "img/jugadores/H/harlen.png"},
  
   { nombre: "F.Aguilar", edad: 33, media: 66, posicion: "DFC" , foto: "img/jugadores/F/faguilar.png"},
   { nombre: "L.Orejuela", edad: 30, media: 64, posicion: "LD"  , foto: "img/jugadores/L/lorejuela.png"},
   { nombre: "S.Arias", edad: 34, media: 77, posicion: "LD" , foto: "img/jugadores/X/arias.png"},
   { nombre: "C.Cuesta", edad: 27, media: 74, posicion: "DFC", foto: "img/jugadores/X/cuesta.png" },
   { nombre: "B.Ceballos", edad: 24, media: 70, posicion: "DFC" , foto: "img/jugadores/X/ceballos.png"},
   { nombre: "C.Devenish", edad: 25, media: 70, posicion: "DFC" , foto: "img/jugadores/X/devenish.png"},
   { nombre: "J.Cuadrado", edad: 37, media: 76, posicion: "LD" , foto: "img/jugadores/X/cuadrado.png"},
   { nombre: "J.Mojica", edad: 33, media: 78, posicion: "LI", foto: "img/jugadores/X/mojica.png" },
   { nombre: "Deiver M.", edad: 32, media: 77, posicion: "LI", foto: "img/jugadores/X/deiver.png" },
   { nombre: "S.Medina", edad: 33, media: 76, posicion: "LD" , foto: "img/jugadores/X/medina.png"},
   { nombre: "W.Ditta", edad: 29, media: 75, posicion: "DFC" , foto: "img/jugadores/X/ditta.png"},
   
   { nombre: "James R.", edad: 34, media: 80, posicion: "MO" , foto: "img/jugadores/X/james.png"},
   { nombre: "Seba Perez", edad: 33, media: 71, posicion: "MD" , foto: "img/jugadores/X/sebas.png"},
   { nombre: "K.Agudelo", edad: 27, media: 68, posicion: "MO" , foto: "img/jugadores/X/agudelo.png"},
   { nombre: "M.Monsalve", edad: 22, media: 67, posicion: "MO" , foto: "img/jugadores/X/monsalve.png"},
   { nombre: "W.Barrios", edad: 32, media: 74, posicion: "MD", foto: "img/jugadores/X/barrios.png" },
   { nombre: "P.Bravo", edad: 21, media: 70, posicion: "MD", foto: "img/jugadores/X/bravo.png" },
   { nombre: "S.Tapiero", edad: 34, media: 67, posicion: "MD" , foto: "img/jugadores/X/tapiero.png"},
   { nombre: "Jordan B.", edad: 19, media: 71, posicion: "MO" , foto: "img/jugadores/X/jordan.png"},

   { nombre: "D.Asprilla", edad: 33, media: 69, posicion: "ED" , foto: "img/jugadores/A/asprilla.png"},
   { nombre: "R.Falcao", edad: 40, media: 73, posicion: "DC"  , foto: "img/jugadores/F/falcao.png"},
   { nombre: "A.Castro", edad: 32, media: 66, posicion: "EI" , foto: "img/jugadores/A/alex.png" },
   { nombre: "Beckham C.", edad: 22, media: 71, posicion: "EI" , foto: "img/jugadores/B/beckham.png"},
   { nombre: "Neyser V.", edad: 20, media: 66, posicion: "DC" , foto: "img/jugadores/X/neyser.png"},
   { nombre: "R.Borre", edad: 30, media: 76, posicion: "DC", foto: "img/jugadores/X/borre.png" },
   { nombre: "Jhon Arias", edad: 28, media: 81, posicion: "ED" , foto: "img/jugadores/X/jhon.png"},
   { nombre: "Marino H.", edad: 23, media: 72, posicion: "ED", foto: "img/jugadores/X/marino.png" },
   { nombre: "J.Enamorado", edad: 27, media: 73, posicion: "ED" , foto: "img/jugadores/X/enamorado.png"},
   { nombre: "K.Viveros", edad: 25, media: 72, posicion: "DC", foto: "img/jugadores/X/viveros.png" },
   { nombre: "D.Zapata", edad: 34, media: 77, posicion: "DC" , foto: "img/jugadores/X/duvan.png"},
   { nombre: "M.Borja", edad: 33, media: 76, posicion: "DC" , foto: "img/jugadores/X/borja.png"},
   { nombre: "S.Villa", edad: 29, media: 77, posicion: "EI" , foto: "img/jugadores/X/villa.png"},
   { nombre: "D.Vergara", edad: 29, media: 76, posicion: "EI", foto: "img/jugadores/X/vergara.png" },
   { nombre: "E.Cetre", edad: 28, media: 76, posicion: "EI" , foto: "img/jugadores/X/cetre.png"},
   { nombre: "K.Serna", edad: 28, media: 67, posicion: "ED" , foto: "img/jugadores/X/serna.png"}
   
  ]
};
